// ========== 完整教材知识库 (v17.2.0) ==========
// 索引编号系统:
// ORG-xxx: 有机化学（第六版）
// DRUG-xxx: 药物化学（第三版）
// PHARM-xxx: 药理学（第九版）
// SYNTH-xxx: 药物合成反应（第四版）
// BIO-xxx: 生物化学与分子生物学（第10版）

/**
 * 完整教材知识库
 * 每本教材按章节组织，知识点带唯一索引编号
 */
const TEXTBOOK_KNOWLEDGE_BASE = {
  // ============================================================
  // 第一本: 有机化学（第六版）- 天津大学
  // ============================================================
  "有机化学（第六版）": {
    bookCode: "ORG",
    totalChapters: 16,
    chapters: [
      {
        chapter: "第一章 绪论",
        sections: [
          {
            id: "ORG-001",
            title: "有机化合物和有机化学",
            content: "有机化合物是含碳化合物（碳氢化合物及其衍生物）。有机化学是研究有机化合物的来源、制备、结构、性质、应用以及有关理论的科学。",
            keywords: ["有机化合物", "有机化学", "碳氢化合物"],
          },
          {
            id: "ORG-002",
            title: "有机化合物的特点",
            content: "1. 可燃 2. 熔点低 3. 难溶于水 4. 反应速率慢 5. 反应产物复杂 6. 同分异构现象普遍",
            keywords: ["熔点", "溶解性", "同分异构"],
          },
          {
            id: "ORG-003",
            title: "有机化合物的结构",
            content: "凯库勒结构式、路易斯结构式、构造式。共价键的键长、键角、键能。",
            keywords: ["凯库勒", "路易斯", "共价键", "键长", "键角", "键能"],
          },
          {
            id: "ORG-004",
            title: "共价键的断裂方式",
            content: "1. 均裂：形成自由基，自由基反应 2. 异裂：形成离子，离子型反应",
            keywords: ["均裂", "异裂", "自由基", "离子型反应"],
          },
          {
            id: "ORG-005",
            title: "有机反应的类型",
            content: "1. 自由基反应 2. 离子型反应（亲电、亲核） 3. 协同反应",
            keywords: ["自由基反应", "亲电反应", "亲核反应", "协同反应"],
          },
        ],
      },
      {
        chapter: "第二章 烷烃",
        sections: [
          {
            id: "ORG-101",
            title: "烷烃的通式和同系列",
            content: "烷烃通式 CnH2n+2。同系列：具有同一通式、结构和性质相似、相互间相差一个或几个 CH2 的一系列化合物。",
            formula: "\\chemfig{C_nH_{2n+2}}",
            mechanism: "",
            conditions: "",
            keywords: ["通式", "同系列", "同系物", "CH2"],
          },
          {
            id: "ORG-102",
            title: "烷烃的命名",
            content: "1. 普通命名法：正、异、新 2. 系统命名法（IUPAC）：选主链、编号、写名称",
            formula: "",
            mechanism: "",
            conditions: "",
            keywords: ["普通命名", "系统命名", "IUPAC", "主链"],
          },
          {
            id: "ORG-103",
            title: "烷烃的结构",
            content: "sp3 杂化，四面体构型，键角 109.5°。σ 键：可以自由旋转。",
            formula: "",
            mechanism: "碳原子的 2s 和三个 2p 轨道杂化形成四个 sp³ 杂化轨道，指向正四面体的四个顶点。C-C σ 键：沿键轴方向头碰头重叠，可以自由旋转。",
            conditions: "",
            keywords: ["sp3杂化", "四面体", "σ键", "109.5°"],
          },
          {
            id: "ORG-104",
            title: "乙烷的构象",
            content: "交叉式和重叠式。交叉式能量最低，重叠式能量最高。纽曼投影式。",
            formula: "",
            mechanism: "交叉式：两个碳原子上的 C-H 键相距最远，排斥力最小，能量最低。重叠式：两个碳原子上的 C-H 键正对，排斥力最大，能量最高。",
            conditions: "",
            keywords: ["构象", "交叉式", "重叠式", "纽曼投影", "乙烷"],
          },
          {
            id: "ORG-105",
            title: "丁烷的构象",
            content: "对位交叉式（最稳定）、邻位交叉式、部分重叠式、全重叠式（最不稳定）。",
            formula: "",
            mechanism: "对位交叉式：两个甲基相距最远，空间位阻最小，能量最低。全重叠式：两个甲基正对，空间位阻最大，能量最高。",
            conditions: "",
            keywords: ["丁烷", "对位交叉", "邻位交叉", "重叠式"],
          },
          {
            id: "ORG-106",
            title: "烷烃的物理性质",
            content: "沸点：随分子量增加而升高，支链越多沸点越低。熔点：随分子量增加而升高，对称性高熔点高。",
            formula: "",
            mechanism: "",
            conditions: "状态：C1-C4 气体，C5-C16 液体，C17+ 固体。密度：随分子量增加而增大，但都小于水。",
            keywords: ["沸点", "熔点", "分子量", "支链"],
          },
          {
            id: "ORG-107",
            title: "烷烃的化学性质 - 卤代反应",
            content: "自由基卤代反应。链引发、链增长、链终止。活性：F2 > Cl2 > Br2 > I2。",
            formula: "\\chemfig{CH_4} + Cl_2 \\xrightarrow{光照} \\chemfig{CH_3Cl} + HCl",
            mechanism: "自由基链式反应：\n1. 链引发：Cl₂ → 2Cl·（光照）\n2. 链传递：Cl· + CH₄ → ·CH₃ + HCl；·CH₃ + Cl₂ → CH₃Cl + Cl·\n3. 链终止：自由基之间结合",
            conditions: "光照（紫外光）或加热（250-400°C）。氟代剧烈，氯代适中，溴代较慢，碘代不反应。",
            keywords: ["卤代反应", "自由基", "链引发", "链增长", "链终止"],
          },
          {
            id: "ORG-108",
            title: "烷烃的氧化反应",
            content: "燃烧生成 CO2 和 H2O，放出大量热。部分氧化生成醇、醛、酮等。",
            formula: "\\chemfig{CH_4} + 2O_2 \\xrightarrow{点燃} CO_2 + 2H_2O + 890 kJ/mol",
            mechanism: "",
            conditions: "点燃或催化剂。完全燃烧生成 CO₂ 和 H₂O；不完全燃烧生成 CO 或碳黑。",
            keywords: ["氧化", "燃烧", "CO2", "放热"],
          },
        ],
      },
      {
        chapter: "第三章 烯烃",
        sections: [
          {
            id: "ORG-201",
            title: "烯烃的结构",
            content: "sp2 杂化，平面构型，键角 ~120°。π 键：不能自由旋转。C=C 双键：一个 σ 键 + 一个 π 键。",
            keywords: ["sp2杂化", "π键", "双键", "120°"],
          },
          {
            id: "ORG-202",
            title: "烯烃的异构现象",
            content: "碳链异构、位置异构、顺反异构（几何异构）。顺反异构：双键两端各连不同基团。",
            keywords: ["顺反异构", "几何异构", "碳链异构", "位置异构"],
          },
          {
            id: "ORG-203",
            title: "烯烃的命名",
            content: "选含双键的最长碳链为主链，编号从靠近双键的一端开始。Z/E 命名法。",
            formula: "",
            mechanism: "",
            conditions: "",
            keywords: ["Z/E", "双键编号", "主链"],
          },
          {
            id: "ORG-204",
            title: "烯烃的亲电加成反应",
            content: "1. 加 HX：马氏规则 2. 加 H2O：酸催化，马氏规则 3. 加 X2：邻二卤代物 4. 加 HOX：卤代醇",
            formula: "\\chemfig{CH_2=CH_2} + Br_2 \\to \\chemfig{BrCH_2-CH_2Br}",
            mechanism: "第一步：亲电试剂（如 Br₂）极化，正电部分进攻双键，形成环正离子中间体（溴鎓离子）。第二步：亲核试剂从背面进攻，开环生成反式加成产物。",
            conditions: "加 HX：气体或浓水溶液；加 H₂O：酸催化（H₂SO₄）；加 X₂：CCl₄ 溶剂，室温；加 HOX：次卤酸水溶液。",
            keywords: ["亲电加成", "马氏规则", "HX", "H2O", "X2"],
          },
          {
            id: "ORG-205",
            title: "马氏规则",
            content: "不对称烯烃与不对称试剂加成时，试剂中的正性部分加在含氢较多的双键碳上。",
            formula: "\\chemfig{CH_3-CH=CH_2} + HBr \\to \\chemfig{CH_3-CHBr-CH_3} (主产物)",
            mechanism: "碳正离子中间体的稳定性：叔碳正离子 > 仲碳正离子 > 伯碳正离子。H⁺ 优先加到含氢较多的碳上，形成更稳定的碳正离子。",
            conditions: "无过氧化物存在时适用。",
            keywords: ["马氏规则", "不对称烯烃", "正性部分"],
          },
          {
            id: "ORG-206",
            title: "过氧化物效应",
            content: "在过氧化物存在下，HBr 加成遵循反马氏规则。自由基加成机制。",
            formula: "\\chemfig{CH_3-CH=CH_2} + HBr \\xrightarrow{ROOR} \\chemfig{CH_3-CH_2-CH_2Br} (主产物)",
            mechanism: "自由基加成：过氧化物分解产生自由基，引发 HBr 均裂生成 Br·，Br· 加到双键上形成更稳定的碳自由基。",
            conditions: "只有 HBr 有过氧化物效应，HCl 和 HI 没有。",
            keywords: ["过氧化物效应", "反马氏", "自由基", "HBr"],
          },
          {
            id: "ORG-207",
            title: "烯烃的氧化反应",
            content: "1. 催化氧化：环氧乙烷 2. 高锰酸钾氧化：邻二醇（冷稀）/ 断裂（加热） 3. 臭氧化：醛/酮",
            formula: "\\chemfig{CH_2=CH_2} \\xrightarrow{KMnO_4, H^+, \\Delta} CO_2 + H_2O",
            mechanism: "冷稀 KMnO₄：顺式加成，生成邻二醇。热浓 KMnO₄：双键断裂，生成羧酸或酮。臭氧化：生成臭氧化物，水解生成醛或酮。",
            conditions: "冷稀 KMnO₄：低温，中性或碱性；热浓 KMnO₄：加热，酸性；臭氧化：O₃，然后 Zn/H₂O。",
            keywords: ["氧化", "高锰酸钾", "臭氧化", "环氧乙烷"],
          },
          {
            id: "ORG-208",
            title: "烯烃的聚合反应",
            content: "加聚反应。乙烯 → 聚乙烯，丙烯 → 聚丙烯。",
            formula: "\\chemfig{n CH_2=CH_2} \\xrightarrow{催化剂} \\chemfig{(-CH_2-CH_2-)}_n",
            mechanism: "连锁聚合反应：引发剂产生活性中心（自由基或离子），引发单体加成，链增长，链终止。",
            conditions: "催化剂（Ziegler-Natta 或过氧化物），高温高压。",
            keywords: ["聚合", "加聚", "聚乙烯", "聚丙烯"],
          },
        ],
      },
      {
        chapter: "第四章 炔烃和二烯烃",
        sections: [
          {
            id: "ORG-301",
            title: "炔烃的结构",
            content: "sp 杂化，直线构型，键角 180°。C≡C 三键：一个 σ 键 + 两个 π 键。",
            keywords: ["sp杂化", "三键", "180°", "直线"],
          },
          {
            id: "ORG-302",
            title: "炔烃的加成反应",
            content: "1. 加 H2：先烯后烷 2. 加 X2：反式加成 3. 加 HX：马氏规则 4. 加 H2O：醛酮（互变异构）",
            keywords: ["炔烃", "加成", "互变异构", "炔醛"],
          },
          {
            id: "ORG-303",
            title: "炔烃的酸性",
            content: "端基炔氢有弱酸性（pKa ~25）。可与银氨溶液、亚铜氨溶液生成炔化物沉淀。",
            keywords: ["端基炔", "酸性", "银氨溶液", "炔化物"],
          },
          {
            id: "ORG-304",
            title: "二烯烃的分类",
            content: "1. 累积二烯烃 2. 孤立二烯烃 3. 共轭二烯烃",
            formula: "",
            mechanism: "",
            conditions: "",
            keywords: ["二烯烃", "共轭", "累积", "孤立"],
          },
          {
            id: "ORG-305",
            title: "共轭二烯烃的结构",
            content: "共轭效应：π 电子离域，键长平均化，体系能量降低。",
            formula: "\\chemfig{CH_2=CH-CH=CH_2}",
            mechanism: "四个碳原子均为 sp² 杂化，p 轨道侧面重叠形成连续的共轭体系。π 电子不再定域在两个碳原子之间，而是离域到整个共轭体系。",
            conditions: "",
            keywords: ["共轭效应", "离域", "键长平均化", "π电子"],
          },
          {
            id: "ORG-306",
            title: "共轭二烯烃的加成",
            content: "1,2-加成和 1,4-加成。低温以 1,2-加成为主，高温以 1,4-加成为主。",
            formula: "\\chemfig{CH_2=CH-CH=CH_2} + Br_2 \\to \\chemfig{BrCH_2-CH=CH-CH_2Br} (1,4-加成)",
            mechanism: "亲电加成：H⁺ 加到 C1 上，形成烯丙基碳正离子（共振杂化体），正电荷分布在 C2 和 C4 上。Br⁻ 可以进攻 C2（1,2-加成）或 C4（1,4-加成）。",
            conditions: "低温（-80°C）：动力学控制，1,2-加成为主；高温（40°C）：热力学控制，1,4-加成为主。",
            keywords: ["1,2-加成", "1,4-加成", "共轭加成"],
          },
          {
            id: "ORG-307",
            title: "Diels-Alder 反应",
            content: "共轭二烯烃与亲双烯体（烯烃/炔烃）反应生成环己烯。协同反应，顺式加成。",
            formula: "\\chemfig{CH_2=CH-CH=CH_2} + \\chemfig{CH_2=CH_2} \\to \\chemfig{*6(-=-=-=)}",
            mechanism: "协同反应：旧键断裂和新键形成同时进行，经过一个环状过渡态。顺式加成：亲双烯体的构型保持不变。",
            conditions: "加热，通常无催化剂。吸电子基团取代的亲双烯体反应更快。",
            keywords: ["Diels-Alder", "双烯合成", "协同反应", "环己烯"],
          },
        ],
      },
      {
        chapter: "第五章 脂环烃",
        sections: [
          {
            id: "ORG-401",
            title: "脂环烃的分类",
            content: "单环、多环（螺环、桥环）。环烷烃通式 CnH2n。",
            formula: "",
            mechanism: "",
            conditions: "",
            keywords: ["脂环烃", "单环", "螺环", "桥环"],
          },
          {
            id: "ORG-402",
            title: "环烷烃的命名",
            content: "单环：环某烷。取代基编号最小。桥环：桥头碳编号。",
            formula: "",
            mechanism: "",
            conditions: "",
            keywords: ["环烷烃", "命名", "桥头碳"],
          },
          {
            id: "ORG-403",
            title: "环烷烃的稳定性",
            content: "小环（3-4元）不稳定，中环（5-6元）稳定。拜尔张力学说。",
            formula: "",
            mechanism: "环张力来自角张力和扭转张力。小环中 sp³ 杂化碳的键角被迫偏离 109.5°，产生角张力。环丙烷 60°，环丁烷 90°，张力最大。",
            conditions: "环戊烷和环己烷键角接近 109.5°，张力最小，最稳定。",
            keywords: ["环张力", "拜尔学说", "稳定性"],
          },
          {
            id: "ORG-404",
            title: "环己烷的构象",
            content: "椅式（最稳定）、船式（不稳定）。直立键（a键）和平伏键（e键）。取代基优先在 e 键。",
            formula: "\\chemfig{*6(------)}",
            mechanism: "椅式构象中，所有 C-C 键角均为 109.5°，无角张力。相邻碳上的 C-H 键全为交叉式构象，无扭转张力。e 键取代基空间位阻小，比 a 键稳定。",
            conditions: "室温下，椅式构象占 99.9%。单取代环己烷中，e 键构象占优势。",
            keywords: ["环己烷", "椅式", "船式", "直立键", "平伏键"],
          },
        ],
      },
      {
        chapter: "第六章 对映异构",
        sections: [
          {
            id: "ORG-501",
            title: "偏振光和旋光性",
            content: "偏振光：只在一个平面振动的光。旋光性：使偏振光振动平面旋转的性质。",
            formula: "",
            mechanism: "尼科尔棱镜将自然光变为偏振光。手性分子使偏振光振动平面旋转。右旋（+）：顺时针；左旋（-）：逆时针。",
            conditions: "旋光度与温度、光源波长、溶液浓度、样品管长度有关。",
            keywords: ["偏振光", "旋光性", "右旋", "左旋"],
          },
          {
            id: "ORG-502",
            title: "手性和手性分子",
            content: "手性：物体与其镜像不能重合的性质。手性分子：与其镜像不能重合的分子。",
            formula: "",
            mechanism: "手性的本质：分子中没有对称面、对称中心或更迭对称轴。最常见的是手性碳原子（连有四个不同基团的 sp³ 碳）。",
            conditions: "",
            keywords: ["手性", "手性分子", "镜像", "重合"],
          },
          {
            id: "ORG-503",
            title: "手性碳和对映异构体",
            content: "手性碳：连有四个不同基团的碳原子。对映异构体：互为镜像但不重合的异构体。",
            formula: "",
            mechanism: "对映异构体物理性质相同（除旋光方向相反），化学性质在非手性环境中相同，在手性环境中不同（如与手性试剂反应、与酶结合）。",
            conditions: "",
            keywords: ["手性碳", "对映异构", "镜像"],
          },
          {
            id: "ORG-504",
            title: "Fischer 投影式",
            content: "横线代表向前，竖线代表向后。碳链竖直，氧化态高的在上。",
            formula: "",
            mechanism: "Fischer 投影式规则：1. 横线向前，竖线向后；2. 碳链竖直，氧化态高的碳在上；3. 不能离开纸面旋转；4. 可以在纸面内旋转 180°，不能旋转 90°。",
            conditions: "",
            keywords: ["Fischer", "投影式", "横线", "竖线"],
          },
          {
            id: "ORG-505",
            title: "R/S 构型标记",
            content: "1. 按次序规则排列基团 2. 最小基团放在最远 3. 观察 1→2→3 方向：顺时针 R，逆时针 S",
            formula: "",
            mechanism: "次序规则：1. 比较原子序数，大者优先；2. 双键/三键视为连接两个/三个相同原子；3. 同位素质量数大者优先。",
            conditions: "",
            keywords: ["R构型", "S构型", "次序规则", "标记"],
          },
          {
            id: "ORG-506",
            title: "含一个手性碳的化合物",
            content: "有一对对映异构体。外消旋体：等量对映体的混合物。",
            formula: "",
            mechanism: "外消旋体（±）无旋光性，因为左旋和右旋的旋光性相互抵消。外消旋体可以通过手性拆分（如手性色谱、成盐拆分）分离为纯对映体。",
            conditions: "",
            keywords: ["手性碳", "对映体", "外消旋体"],
          },
          {
            id: "ORG-507",
            title: "含两个手性碳的化合物",
            content: "1. 两个不同手性碳：4 个立体异构体（两对对映体） 2. 两个相同手性碳：3 个立体异构体（一对对映体 + 一个内消旋体）",
            formula: "",
            mechanism: "内消旋体（meso）：分子内有两个相同手性碳，但分子有对称面，旋光性内部抵消。内消旋体是纯净物，不是混合物。非对映体：不互为镜像的立体异构体。",
            conditions: "",
            keywords: ["两个手性碳", "内消旋体", "非对映体"],
          },
        ],
      },
      {
        chapter: "第七章 芳烃",
        sections: [
          {
            id: "ORG-601",
            title: "苯的结构",
            content: "sp2 杂化，平面正六边形，键角 120°。大 π 键：π 电子离域。",
            keywords: ["苯", "sp2杂化", "大π键", "离域", "正六边形"],
          },
          {
            id: "ORG-602",
            title: "苯的命名",
            content: "烷基苯：苯为母体。多取代苯：编号最小。邻(o-)、间(m-)、对(p-)。",
            keywords: ["苯", "命名", "邻位", "间位", "对位"],
          },
          {
            id: "ORG-603",
            title: "苯的亲电取代反应",
            content: "1. 卤代：苯 + Cl2/FeCl3 → 氯苯 2. 硝化：苯 + 浓HNO3/浓H2SO4 → 硝基苯 3. 磺化：苯 + 浓H2SO4 → 苯磺酸 4. Friedel-Crafts 反应：烷基化、酰基化",
            formula: "\\chemfig{*6(-=-=-=)} + Br_2 \\xrightarrow{FeBr_3} \\chemfig{*6(-=-=-Br-)} + HBr",
            mechanism: "亲电取代机理：1. 亲电试剂（如 Br⁺）进攻苯环，形成 σ 络合物（碳正离子中间体）；2. σ 络合物脱去质子，恢复芳香性。",
            conditions: "卤代：FeBr₃/FeCl₃ 催化；硝化：浓 HNO₃ + 浓 H₂SO₄，50-60°C；磺化：发烟 H₂SO₄，加热；Friedel-Crafts：AlCl₃ 催化。",
            keywords: ["亲电取代", "卤代", "硝化", "磺化", "Friedel-Crafts"],
          },
          {
            id: "ORG-604",
            title: "亲电取代反应历程",
            content: "1. 亲电试剂进攻，形成 σ 络合物（碳正离子中间体） 2. 脱去质子，恢复芳香性",
            formula: "",
            mechanism: "第一步：亲电试剂进攻苯环，形成非芳香性的 σ 络合物（碳正离子中间体），这是决速步。第二步：脱去质子，恢复芳香性，生成产物。",
            conditions: "",
            keywords: ["亲电取代", "σ络合物", "碳正离子", "中间体"],
          },
          {
            id: "ORG-605",
            title: "定位效应",
            content: "邻对位定位基（第一类）：-NH2, -OH, -OR, -R, -X 间位定位基（第二类）：-NO2, -CN, -SO3H, -CHO, -COOH",
            formula: "",
            mechanism: "邻对位定位基：给电子基团，使苯环电子云密度增加，活化苯环，新取代基进入邻位和对位。间位定位基：吸电子基团，使苯环电子云密度降低，钝化苯环，新取代基进入间位。",
            conditions: "",
            keywords: ["定位效应", "邻对位", "间位", "定位基"],
          },
          {
            id: "ORG-606",
            title: "苯的侧链反应",
            content: "1. 侧链氧化：烷基苯 + KMnO4 → 苯甲酸 2. 侧链卤代：光照下 α-卤代",
            formula: "\\chemfig{*6(-=-=-CH_3-)} \\xrightarrow{KMnO_4, H^+, \\Delta} \\chemfig{*6(-=-=-COOH-)}",
            mechanism: "侧链氧化：无论侧链长短，只要有 α-H，最终都氧化为苯甲酸。侧链卤代：自由基机理，光照下 α-H 被卤素取代。",
            conditions: "氧化：KMnO₄/K₂Cr₂O₇，酸性，加热；卤代：光照，Cl₂/Br₂。",
            keywords: ["侧链氧化", "侧链卤代", "烷基苯"],
          },
          {
            id: "ORG-607",
            title: "稠环芳烃",
            content: "萘、蒽、菲。萘的亲电取代：α 位活性高。",
            formula: "\\chemfig{*6(-=-=-=*6(=-=-=-))}",
            mechanism: "萘的 α 位电子云密度比 β 位高，亲电取代优先发生在 α 位。蒽和菲的亲电取代优先发生在 9,10 位。",
            conditions: "萘的硝化：低温，主要 α-硝基萘；磺化：低温 α 位为主，高温 β 位为主。",
            keywords: ["稠环芳烃", "萘", "蒽", "菲", "α位"],
          },
        ],
      },
      {
        chapter: "第八章 卤代烃",
        sections: [
          {
            id: "ORG-701",
            title: "卤代烃的分类和命名",
            content: "分类：伯、仲、叔卤代烃。命名：选含卤原子的最长碳链为主链。",
            formula: "",
            mechanism: "",
            conditions: "",
            keywords: ["卤代烃", "伯仲叔", "分类", "命名"],
          },
          {
            id: "ORG-702",
            title: "亲核取代反应 (SN1/SN2)",
            content: "SN1：单分子，两步，碳正离子中间体，外消旋化，叔 > 仲 > 伯 SN2：双分子，一步，背面进攻，构型翻转，伯 > 仲 > 叔",
            formula: "",
            mechanism: "SN1：第一步卤离子离去形成碳正离子（决速步），第二步亲核试剂进攻。SN2：亲核试剂从背面进攻，同时离去基团离开，构型翻转（Walden 翻转）。",
            conditions: "SN1：极性溶剂，叔卤代烷有利；SN2：非极性溶剂，伯卤代烷有利。",
            keywords: ["SN1", "SN2", "亲核取代", "碳正离子", "构型翻转", "Walden"],
          },
          {
            id: "ORG-703",
            title: "消除反应 (E1/E2)",
            content: "E1：单分子，两步，碳正离子中间体 E2：双分子，一步，反式消除",
            formula: "",
            mechanism: "E1：与 SN1 竞争，第一步形成碳正离子，第二步脱去 β-H。E2：与 SN2 竞争，碱夺取 β-H，同时离去基团离开，反式共平面消除。",
            conditions: "E1：极性溶剂，高温；E2：强碱，高温。札伊采夫规则：消除产物以取代基多的烯烃为主。",
            keywords: ["消除反应", "E1", "E2", "反式消除"],
          },
          {
            id: "ORG-704",
            title: "格氏试剂",
            content: "卤代烷 + Mg → RMgX。与醛酮反应生成醇。与 CO2 反应生成羧酸。",
            formula: "\\chemfig{R-X} + Mg \\xrightarrow{无水乙醚} \\chemfig{R-MgX}",
            mechanism: "格氏试剂是强亲核试剂和强碱。与醛反应生成伯醇，与酮反应生成仲醇，与 CO₂ 反应生成多一个碳的羧酸。",
            conditions: "无水乙醚或 THF 溶剂，严格无水无氧。",
            keywords: ["格氏试剂", "RMgX", "醇", "羧酸"],
          },
        ],
      },
      {
        chapter: "第九章 醇和醚",
        sections: [
          {
            id: "ORG-801",
            title: "醇的结构和命名",
            content: "醇：羟基 (-OH) 连在饱和碳上。分类：伯、仲、叔醇。命名：选含羟基的最长碳链为主链。",
            keywords: ["醇", "羟基", "伯仲叔", "命名"],
          },
          {
            id: "ORG-802",
            title: "醇的物理性质",
            content: "沸点高：氢键作用。水溶性：低级醇与水互溶。",
            keywords: ["醇", "沸点", "氢键", "水溶性"],
          },
          {
            id: "ORG-803",
            title: "醇的化学性质 - 与活泼金属反应",
            content: "醇 + Na → 醇钠 + H2。酸性：甲醇 > 伯醇 > 仲醇 > 叔醇。",
            formula: "\\chemfig{2 R-OH} + 2 Na \\to \\chemfig{2 R-ONa} + H_2\\uparrow",
            mechanism: "醇羟基的 O-H 键断裂，氢被金属钠取代，放出氢气。烷基给电子效应使氧上电子云密度增加，O-H 键极性减弱，酸性降低。",
            conditions: "无水条件，钠块缓慢反应。",
            keywords: ["醇钠", "Na", "酸性"],
          },
          {
            id: "ORG-804",
            title: "醇的化学性质 - 与氢卤酸反应",
            content: "醇 + HX → 卤代烷 + H2O。活性：叔醇 > 仲醇 > 伯醇。Lucas 试剂鉴别伯仲叔醇。",
            formula: "\\chemfig{R-OH} + HX \\to \\chemfig{R-X} + H_2O",
            mechanism: "叔醇和仲醇：SN1 机理，先质子化，再脱水形成碳正离子，最后卤离子进攻。伯醇：SN2 机理。",
            conditions: "Lucas 试剂（浓 HCl + ZnCl₂）：叔醇立即浑浊，仲醇数分钟浑浊，伯醇室温不反应。",
            keywords: ["氢卤酸", "卤代烷", "Lucas试剂", "鉴别"],
          },
          {
            id: "ORG-805",
            title: "醇的化学性质 - 脱水反应",
            content: "分子内脱水：醇 → 烯烃（酸催化，高温） 分子间脱水：醇 → 醚（酸催化，低温）",
            formula: "\\chemfig{CH_3CH_2OH} \\xrightarrow{浓H_2SO_4, 170^\\circ C} \\chemfig{CH_2=CH_2} + H_2O",
            mechanism: "分子内脱水：E1 机理，先质子化，再脱水形成碳正离子，最后脱去 β-H。札伊采夫规则：取代基多的烯烃为主。",
            conditions: "分子内脱水：浓 H₂SO₄，高温（170°C）；分子间脱水：浓 H₂SO₄，低温（140°C）。",
            keywords: ["脱水", "烯烃", "醚", "分子内", "分子间"],
          },
          {
            id: "ORG-806",
            title: "醇的氧化反应",
            content: "伯醇 → 醛 → 羧酸 仲醇 → 酮 叔醇：难氧化（条件剧烈时断裂）",
            formula: "\\chemfig{R-CH_2OH} \\xrightarrow{KMnO_4, H^+} \\chemfig{R-CHO} \\xrightarrow{KMnO_4, H^+} \\chemfig{R-COOH}",
            mechanism: "伯醇先氧化为醛，醛继续氧化为羧酸。仲醇氧化为酮，酮难继续氧化。叔醇无 α-H，条件剧烈时碳碳键断裂。",
            conditions: "强氧化：KMnO₄/K₂Cr₂O₇，酸性，加热；温和氧化：PCC（吡啶氯铬酸盐），伯醇停在醛。",
            keywords: ["氧化", "伯醇", "仲醇", "叔醇", "醛", "酮", "羧酸"],
          },
          {
            id: "ORG-807",
            title: "醚的结构和性质",
            content: "醚：C-O-C。性质稳定，常用溶剂。醚键的断裂：HI 或 HBr。",
            formula: "\\chemfig{R-O-R'}",
            mechanism: "醚键断裂：浓 HI 或 HBr 加热，醚氧先质子化，然后卤离子进攻取代基，生成醇和卤代烷。",
            conditions: "浓 HI 或 HBr，加热。芳基烷基醚断裂生成酚和卤代烷。",
            keywords: ["醚", "醚键", "溶剂", "断裂"],
          },
        ],
      },
      {
        chapter: "第十章 醛和酮",
        sections: [
          {
            id: "ORG-901",
            title: "醛和酮的结构",
            content: "羰基 C=O。醛：-CHO（端基） 酮：C=O（中间）。sp2 杂化，平面构型。",
            keywords: ["醛", "酮", "羰基", "C=O", "sp2杂化"],
          },
          {
            id: "ORG-902",
            title: "醛和酮的命名",
            content: "选含羰基的最长碳链为主链，编号从靠近羰基的一端开始。",
            keywords: ["命名", "羰基编号", "主链"],
          },
          {
            id: "ORG-903",
            title: "羰基的亲核加成反应",
            content: "1. 加 HCN：α-羟基腈 2. 加 NaHSO3：α-羟基磺酸钠 3. 加 RMgX：醇 4. 加醇：缩醛/缩酮 5. 加氨衍生物：肟、腙等",
            formula: "\\chemfig{R-CHO} + HCN \\to \\chemfig{R-CH(OH)-CN}",
            mechanism: "亲核加成机理：亲核试剂进攻羰基碳，π 键断裂，氧带负电，再质子化。羰基碳正电性越强，反应越容易。",
            conditions: "HCN：碱催化；NaHSO₃：饱和溶液，醛和甲基酮；格氏试剂：无水乙醚；缩醛：干燥 HCl 催化。",
            keywords: ["亲核加成", "HCN", "NaHSO3", "格氏试剂", "缩醛", "肟", "腙"],
          },
          {
            id: "ORG-904",
            title: "醛酮的氧化反应",
            content: "醛易氧化：Tollens 试剂（银镜反应）、Fehling 试剂（砖红色沉淀） 酮难氧化",
            formula: "\\chemfig{R-CHO} + 2 Ag(NH_3)_2OH \\to \\chemfig{R-COONH_4} + 2 Ag\\downarrow + 3 NH_3 + H_2O",
            mechanism: "醛基的 C-H 键易被氧化为 C-OH（羧基）。酮羰基两侧都是碳，难以氧化。",
            conditions: "Tollens 试剂：银氨溶液，水浴加热，银镜反应；Fehling 试剂：硫酸铜+酒石酸钾钠+NaOH，砖红色沉淀（Cu₂O）。",
            keywords: ["氧化", "Tollens", "Fehling", "银镜反应", "醛"],
          },
          {
            id: "ORG-905",
            title: "醛酮的还原反应",
            content: "1. 催化加氢：醇 2. NaBH4：醇（温和） 3. LiAlH4：醇（强） 4. Clemmensen 还原：亚甲基",
            formula: "\\chemfig{R-CHO} \\xrightarrow{NaBH_4, EtOH} \\chemfig{R-CH_2OH}",
            mechanism: "催化加氢：H₂/Pd，C=O 还原为 CH-OH。NaBH₄：温和还原剂，只还原醛酮。LiAlH₄：强还原剂，还原醛酮羧酸酯。Clemmensen：Zn-Hg/HCl，羰基还原为亚甲基。",
            conditions: "NaBH₄：乙醇溶剂，室温；LiAlH₄：无水乙醚；Clemmensen：浓 HCl，回流。",
            keywords: ["还原", "NaBH4", "LiAlH4", "Clemmensen", "亚甲基"],
          },
          {
            id: "ORG-906",
            title: "羟醛缩合反应",
            content: "稀碱催化下，两分子醛（有 α-H）缩合生成 β-羟基醛。加热脱水生成 α,β-不饱和醛。",
            formula: "\\chemfig{2 CH_3CHO} \\xrightarrow{稀OH^-} \\chemfig{CH_3CH(OH)CH_2CHO}",
            mechanism: "第一步：碱夺取 α-H，形成烯醇负离子；第二步：烯醇负离子进攻另一分子醛的羰基，发生亲核加成；第三步：质子化生成 β-羟基醛。",
            conditions: "稀 NaOH 水溶液，低温（5°C）。加热脱水生成 α,β-不饱和醛。",
            keywords: ["羟醛缩合", "α-H", "β-羟基醛", "脱水"],
          },
          {
            id: "ORG-907",
            title: "卤仿反应",
            content: "甲基酮 + 卤素 + 碱 → 卤仿（CHX3）+ 羧酸盐。碘仿反应用于鉴别甲基酮。",
            formula: "\\chemfig{CH_3CO-R} + 3 I_2 + 4 NaOH \\to \\chemfig{CHI_3}\\downarrow + \\chemfig{R-COONa} + 3 NaI + 3 H_2O",
            mechanism: "甲基酮的三个 α-H 被卤素取代，生成 CX₃-CO-R，然后碱断裂 C-C 键，生成卤仿和羧酸盐。",
            conditions: "I₂/NaOH，加热。碘仿（CHI₃）为黄色沉淀，用于鉴别甲基酮和能氧化为甲基酮的醇。",
            keywords: ["卤仿反应", "甲基酮", "碘仿", "鉴别"],
          },
        ],
      },
      {
        chapter: "第十一章 羧酸",
        sections: [
          {
            id: "ORG-1001",
            title: "羧酸的结构和命名",
            content: "羧基 -COOH。命名：选含羧基的最长碳链为主链，编号从羧基碳开始。",
            formula: "\\chemfig{R-COOH}",
            mechanism: "羧基中羰基和羟基形成 p-π 共轭，羧基碳的亲电性降低，羟基的 O-H 键极性增强。",
            conditions: "",
            keywords: ["羧酸", "羧基", "命名", "COOH"],
          },
          {
            id: "ORG-1002",
            title: "羧酸的酸性",
            content: "羧酸有酸性（pKa ~5）。取代基对酸性的影响：吸电子基增强酸性，给电子基减弱酸性。",
            formula: "\\chemfig{R-COOH} \\rightleftharpoons \\chemfig{R-COO^-} + H^+",
            mechanism: "羧酸根负离子的负电荷通过 p-π 共轭分散到两个氧原子上，稳定性高，所以羧酸有明显酸性。吸电子基进一步分散负电荷，增强酸性。",
            conditions: "",
            keywords: ["酸性", "pKa", "吸电子基", "给电子基"],
          },
          {
            id: "ORG-1003",
            title: "羧酸的化学反应",
            content: "1. 成盐反应 2. 生成酰卤 3. 生成酸酐 4. 生成酯（Fischer 酯化） 5. 生成酰胺",
            formula: "\\chemfig{R-COOH} + R'OH \\xrightleftharpoons{H^+} \\chemfig{R-COOR'} + H_2O",
            mechanism: "Fischer 酯化：酸催化，亲核酰基取代机理。羰基先质子化，增强羰基碳亲电性，然后醇进攻，再脱水。",
            conditions: "成盐：NaOH/Na₂CO₃；酰卤：SOCl₂/PCl₃；酯化：浓 H₂SO₄，回流；酰胺：氨，加热。",
            keywords: ["成盐", "酰卤", "酸酐", "酯化", "酰胺"],
          },
          {
            id: "ORG-1004",
            title: "羧酸的还原",
            content: "LiAlH4 还原羧酸生成伯醇。",
            formula: "\\chemfig{R-COOH} \\xrightarrow{LiAlH_4, 无水乙醚} \\chemfig{R-CH_2OH}",
            mechanism: "LiAlH₄ 是强还原剂，将羧基还原为伯醇。NaBH₄ 不能还原羧酸。",
            conditions: "无水乙醚或 THF，严格无水。",
            keywords: ["还原", "LiAlH4", "伯醇"],
          },
          {
            id: "ORG-1005",
            title: "羧酸衍生物",
            content: "酰卤、酸酐、酯、酰胺。水解活性：酰卤 > 酸酐 > 酯 > 酰胺。",
            formula: "",
            mechanism: "亲核酰基取代：亲核试剂进攻羰基，形成四面体中间体，然后离去基团离开。离去基团越容易离开，活性越高。",
            conditions: "水解：酰卤常温，酸酐加热，酯需酸碱催化，酰胺需强酸/强碱长时间回流。",
            keywords: ["羧酸衍生物", "酰卤", "酸酐", "酯", "酰胺", "水解活性"],
          },
        ],
      },
      {
        chapter: "第十二章 含氮化合物",
        sections: [
          {
            id: "ORG-1101",
            title: "硝基化合物",
            content: "硝基 -NO2。芳香族硝基化合物：还原生成苯胺。",
            formula: "\\chemfig{*6(-=-=-NO_2-)} \\xrightarrow{Fe/HCl} \\chemfig{*6(-=-=-NH_2-)}",
            mechanism: "硝基在酸性条件下还原，经过亚硝基、羟胺中间体，最终生成氨基。",
            conditions: "Fe/HCl 或 Sn/HCl，加热。催化氢化：H₂/Pd。",
            keywords: ["硝基化合物", "硝基", "还原", "苯胺"],
          },
          {
            id: "ORG-1102",
            title: "胺的分类和命名",
            content: "胺：氨基 -NH2。分类：伯、仲、叔胺。命名：选含氨基的最长碳链为主链。",
            formula: "",
            mechanism: "",
            conditions: "",
            keywords: ["胺", "氨基", "伯仲叔", "命名"],
          },
          {
            id: "ORG-1103",
            title: "胺的碱性",
            content: "胺有碱性。脂肪胺 > 氨 > 芳香胺。取代基对碱性的影响。",
            formula: "\\chemfig{R-NH_2} + H_2O \\rightleftharpoons \\chemfig{R-NH_3^+} + OH^-",
            mechanism: "胺氮上有孤对电子，能接受质子显碱性。脂肪胺烷基给电子，使氮上电子云密度增加，碱性增强。芳香胺氮孤对电子与苯环共轭，碱性减弱。",
            conditions: "",
            keywords: ["碱性", "脂肪胺", "芳香胺", "取代基"],
          },
          {
            id: "ORG-1104",
            title: "胺的化学反应",
            content: "1. 烷基化 2. 酰基化 3. 与亚硝酸反应 4. 芳香胺的亲电取代",
            formula: "",
            mechanism: "烷基化：氨/胺与卤代烷反应，生成更高阶的胺。酰基化：胺与酰卤/酸酐反应生成酰胺。与亚硝酸：伯胺生成重氮盐，仲胺生成 N-亚硝基胺。",
            conditions: "烷基化：卤代烷，加热；酰基化：酰卤/酸酐，吡啶；重氮化：NaNO₂/HCl，0-5°C。",
            keywords: ["烷基化", "酰基化", "亚硝酸", "亲电取代"],
          },
          {
            id: "ORG-1105",
            title: "重氮盐",
            content: "芳香伯胺 + 亚硝酸 + 低温 → 重氮盐。重氮盐的取代反应和偶联反应。",
            keywords: ["重氮盐", "亚硝酸", "偶联反应"],
          },
        ],
      },
    ],
  },

  // ============================================================
  // 第二本: 药物化学（第三版）- 尤启冬
  // ============================================================
  "药物化学（第三版）": {
    bookCode: "DRUG",
    totalChapters: 20,
    chapters: [
      {
        chapter: "第一章 绪论",
        sections: [
          {
            id: "DRUG-001",
            title: "药物化学的定义和任务",
            content: "药物化学是研究化学药物的结构、制备、性质、构效关系、体内代谢、寻找新药的一门科学。",
            formula: "",
            mechanism: "核心任务：1. 创制新药：设计、合成新的活性化合物；2. 阐明药物化学结构与活性的关系（构效关系）；3. 研究药物在体内的代谢过程。",
            conditions: "",
            keywords: ["药物化学", "定义", "任务"],
          },
          {
            id: "DRUG-002",
            title: "药物的质量评价",
            content: "1. 有效性 2. 安全性 3. 稳定性 4. 均一性",
            formula: "",
            mechanism: "有效性：药物达到预期疗效的能力；安全性：药物在治疗剂量下不产生严重毒副作用；稳定性：药物在贮存期内保持质量稳定；均一性：药物各批次质量一致。",
            conditions: "",
            keywords: ["质量评价", "有效性", "安全性", "稳定性"],
          },
        ],
      },
      {
        chapter: "第二章 麻醉药",
        sections: [
          {
            id: "DRUG-101",
            title: "全身麻醉药",
            content: "吸入麻醉药：乙醚、氟烷、恩氟烷、异氟烷。静脉麻醉药：硫喷妥钠、氯胺酮。",
            formula: "",
            mechanism: "作用机制：抑制中枢神经系统，产生意识、感觉和反射消失。吸入麻醉药通过血脑屏障，作用于 GABA_A 受体和 NMDA 受体。",
            conditions: "吸入麻醉药：需挥发罐，控制浓度；静脉麻醉药：静脉注射，起效快。",
            keywords: ["全身麻醉药", "吸入麻醉", "静脉麻醉", "乙醚", "氯胺酮"],
          },
          {
            id: "DRUG-102",
            title: "局部麻醉药",
            content: "酯类：普鲁卡因、丁卡因。酰胺类：利多卡因、布比卡因。构效关系：芳环-中间链-氨基。",
            formula: "",
            mechanism: "作用机制：阻断电压门控 Na⁺ 通道，阻止神经冲动传导。芳环提供脂溶性，中间链决定代谢途径，氨基决定水溶性。",
            conditions: "酯类：血浆假性胆碱酯酶水解，作用时间短；酰胺类：肝脏代谢，作用时间长。",
            keywords: ["局部麻醉药", "普鲁卡因", "利多卡因", "构效关系"],
          },
        ],
      },
      {
        chapter: "第三章 镇静催眠药和抗癫痫药",
        sections: [
          {
            id: "DRUG-201",
            title: "巴比妥类",
            content: "苯巴比妥、异戊巴比妥、硫喷妥钠。作用机制：增强 GABA 介导的 Cl- 内流。",
            formula: "",
            mechanism: "作用机制：与 GABA_A 受体结合，延长 Cl⁻ 通道开放时间，增强抑制性突触传递。脂溶性越高，起效越快，作用时间越短。",
            conditions: "苯巴比妥：长效，抗癫痫；异戊巴比妥：中效，镇静催眠；硫喷妥钠：超短效，静脉麻醉。",
            keywords: ["巴比妥", "苯巴比妥", "GABA", "Cl-"],
          },
          {
            id: "DRUG-202",
            title: "苯二氮䓬类",
            content: "地西泮、艾司唑仑、阿普唑仑。作用机制：增强 GABA 与受体的结合。",
            formula: "",
            mechanism: "作用机制：与 GABA_A 受体结合，增加 Cl⁻ 通道开放频率，增强 GABA 的抑制作用。安全性比巴比妥类高。",
            conditions: "地西泮：长效，抗焦虑、催眠；艾司唑仑：中效，催眠；阿普唑仑：短效，抗焦虑。",
            keywords: ["苯二氮䓬", "地西泮", "安定", "GABA"],
          },
          {
            id: "DRUG-203",
            title: "抗癫痫药",
            content: "苯妥英钠、卡马西平、丙戊酸钠。作用机制：稳定细胞膜，抑制异常放电。",
            formula: "",
            mechanism: "苯妥英钠：阻断 Na⁺ 通道，稳定细胞膜；卡马西平：阻断 Na⁺ 通道，用于精神运动性发作；丙戊酸钠：增强 GABA 功能，广谱抗癫痫。",
            conditions: "苯妥英钠：大发作首选；卡马西平：精神运动性发作首选；丙戊酸钠：广谱，各型发作均可。",
            keywords: ["抗癫痫", "苯妥英钠", "卡马西平", "丙戊酸钠"],
          },
        ],
      },
      {
        chapter: "第四章 精神神经疾病治疗药",
        sections: [
          {
            id: "DRUG-301",
            title: "抗精神病药",
            content: "吩噻嗪类：氯丙嗪。丁酰苯类：氟哌啶醇。作用机制：阻断多巴胺受体。",
            formula: "",
            mechanism: "作用机制：阻断中脑-边缘系统和中脑-皮质通路的 D₂ 受体，发挥抗精神病作用。同时阻断黑质-纹状体 D₂ 受体，产生锥体外系副作用。",
            conditions: "氯丙嗪：第一代抗精神病药，副作用多；利培酮：第二代，锥体外系副作用少。",
            keywords: ["抗精神病", "氯丙嗪", "多巴胺受体"],
          },
          {
            id: "DRUG-302",
            title: "抗抑郁药",
            content: "三环类：丙咪嗪。单胺氧化酶抑制剂：吗氯贝胺。SSRIs：氟西汀、帕罗西汀。",
            formula: "",
            mechanism: "三环类：抑制 NA 和 5-HT 再摄取；MAOI：抑制单胺氧化酶，增加单胺类递质；SSRIs：选择性抑制 5-HT 再摄取，副作用少。",
            conditions: "氟西汀（百忧解）：SSRI 类首选，起效慢（2-4 周）。",
            keywords: ["抗抑郁", "氟西汀", "百忧解", "SSRIs"],
          },
        ],
      },
      {
        chapter: "第五章 解热镇痛药和非甾体抗炎药",
        sections: [
          {
            id: "DRUG-401",
            title: "阿司匹林",
            content: "乙酰水杨酸。作用机制：抑制 COX，减少前列腺素合成。临床：解热、镇痛、抗炎、抗血小板。",
            formula: "\\chemfig{*6(-COOH-OCOCH_3-=-=-)}",
            mechanism: "作用机制：不可逆抑制环氧合酶（COX-1 和 COX-2），阻止花生四烯酸转化为前列腺素，发挥解热、镇痛、抗炎作用。小剂量抑制血小板聚集，预防血栓。",
            conditions: "小剂量（75-100mg）：抗血小板；中剂量：解热镇痛；大剂量：抗炎抗风湿。胃溃疡患者慎用。",
            keywords: ["阿司匹林", "乙酰水杨酸", "COX", "前列腺素"],
          },
          {
            id: "DRUG-402",
            title: "对乙酰氨基酚",
            content: "扑热息痛。作用机制：抑制中枢 COX。临床：解热镇痛，抗炎作用弱。",
            formula: "\\chemfig{*6(-NHCOCH_3-OH-=-=-)}",
            mechanism: "作用机制：主要抑制中枢神经系统的 COX，对外周 COX 抑制弱，故解热镇痛作用强，抗炎作用弱。过量可导致肝损伤。",
            conditions: "常规剂量安全；过量（>10g）导致肝坏死，解毒剂为 N-乙酰半胱氨酸。",
            keywords: ["对乙酰氨基酚", "扑热息痛", "解热镇痛"],
          },
          {
            id: "DRUG-403",
            title: "非甾体抗炎药 (NSAIDs)",
            content: "布洛芬、萘普生、双氯芬酸、吲哚美辛。作用机制：抑制 COX。分类：选择性 COX-2 抑制剂。",
            formula: "",
            mechanism: "作用机制：抑制环氧合酶（COX），减少前列腺素合成。COX-1 为结构型，保护胃黏膜；COX-2 为诱导型，介导炎症。选择性 COX-2 抑制剂胃肠道副作用少。",
            conditions: "布洛芬：常用，胃肠道副作用小；双氯芬酸：强效抗炎；吲哚美辛：强效但副作用多。选择性 COX-2 抑制剂（如塞来昔布）胃肠道副作用少，但心血管风险增加。",
            keywords: ["NSAIDs", "布洛芬", "萘普生", "COX-2"],
          },
        ],
      },
      {
        chapter: "第六章 镇痛药",
        sections: [
          {
            id: "DRUG-501",
            title: "吗啡及其衍生物",
            content: "吗啡、可待因、海洛因。作用机制：激动阿片受体。临床：镇痛、镇咳、止泻。",
            formula: "",
            mechanism: "作用机制：激动中枢神经系统的 μ 阿片受体，抑制 P 物质释放，阻断痛觉传导。同时抑制呼吸中枢、镇咳、兴奋延髓催吐化学感受区。",
            conditions: "吗啡：强效镇痛，成瘾性强；可待因：镇咳为主，镇痛弱；海洛因：二乙酰吗啡，成瘾性极强。",
            keywords: ["吗啡", "可待因", "阿片受体", "镇痛"],
          },
          {
            id: "DRUG-502",
            title: "合成镇痛药",
            content: "哌替啶、芬太尼、美沙酮。作用机制：激动阿片受体。",
            formula: "",
            mechanism: "作用机制：激动 μ 阿片受体，发挥镇痛作用。结构虽与吗啡不同，但药效团相似（芳环-叔胺-哌啶环）。",
            conditions: "哌替啶：短效，分娩镇痛；芬太尼：强效，静脉麻醉；美沙酮：长效，戒毒替代治疗。",
            keywords: ["合成镇痛药", "哌替啶", "芬太尼", "美沙酮"],
          },
        ],
      },
      {
        chapter: "第七章 心血管系统药物",
        sections: [
          {
            id: "DRUG-601",
            title: "钙通道阻滞剂",
            content: "二氢吡啶类：硝苯地平、尼莫地平。芳烷基胺类：维拉帕米。苯噻氮䓬类：地尔硫卓。",
            formula: "",
            mechanism: "作用机制：阻断电压门控 L-型钙通道，抑制 Ca²⁺ 内流，松弛血管平滑肌，降低心肌收缩力，减慢心率。",
            conditions: "硝苯地平：扩血管强，降压；维拉帕米：负性频率，抗心律失常；地尔硫卓：介于两者之间。",
            keywords: ["钙通道阻滞剂", "硝苯地平", "维拉帕米", "高血压"],
          },
          {
            id: "DRUG-602",
            title: "ACE 抑制剂",
            content: "卡托普利、依那普利。作用机制：抑制血管紧张素转化酶。临床：高血压、心衰。",
            formula: "",
            mechanism: "作用机制：抑制血管紧张素转化酶（ACE），阻止 Ang I 转化为 Ang II，同时抑制缓激肽降解，扩张血管，降低血压。",
            conditions: "干咳为常见副作用（缓激肽蓄积）。禁忌：双侧肾动脉狭窄、妊娠。",
            keywords: ["ACEI", "卡托普利", "依那普利", "高血压"],
          },
          {
            id: "DRUG-603",
            title: "β 受体阻滞剂",
            content: "普萘洛尔、美托洛尔。作用机制：阻断 β 受体。临床：高血压、心绞痛、心律失常。",
            formula: "",
            mechanism: "作用机制：阻断心脏 β₁ 受体，减慢心率，降低心肌收缩力，减少心肌耗氧量。同时阻断肾脏 β₁ 受体，抑制肾素释放。",
            conditions: "普萘洛尔：非选择性（β₁+β₂）；美托洛尔：选择性 β₁。禁忌：支气管哮喘（阻断 β₂ 可诱发哮喘）。",
            keywords: ["β受体阻滞剂", "普萘洛尔", "美托洛尔", "高血压"],
          },
        ],
      },
      {
        chapter: "第十一章 抗生素",
        sections: [
          {
            id: "DRUG-701",
            title: "β-内酰胺类抗生素",
            content: "青霉素类：青霉素G、阿莫西林。头孢菌素类：头孢氨苄、头孢呋辛。作用机制：抑制细胞壁合成。",
            formula: "",
            mechanism: "作用机制：与青霉素结合蛋白（PBPs）结合，抑制转肽酶活性，阻止肽聚糖交联，导致细菌细胞壁缺损，菌体膨胀裂解。",
            conditions: "青霉素 G：革兰阳性菌首选；阿莫西林：广谱，口服有效；头孢类：分代，代数越高革兰阴性菌覆盖越广。",
            keywords: ["β-内酰胺", "青霉素", "头孢", "细胞壁"],
          },
          {
            id: "DRUG-702",
            title: "大环内酯类抗生素",
            content: "红霉素、阿奇霉素、克拉霉素。作用机制：抑制细菌蛋白质合成。",
            formula: "",
            mechanism: "作用机制：与细菌核糖体 50S 亚基结合，抑制转肽作用和 mRNA 移位，阻止蛋白质合成。",
            conditions: "红霉素：耐青霉素的革兰阳性菌；阿奇霉素：半衰期长，每日一次，非典型病原体首选。",
            keywords: ["大环内酯", "红霉素", "阿奇霉素", "蛋白质合成"],
          },
          {
            id: "DRUG-703",
            title: "氨基糖苷类抗生素",
            content: "链霉素、庆大霉素、阿米卡星。作用机制：抑制细菌蛋白质合成。耳毒性、肾毒性。",
            formula: "",
            mechanism: "作用机制：与细菌核糖体 30S 亚基结合，抑制蛋白质合成，同时导致细胞膜缺损，通透性增加。",
            conditions: "耳毒性（前庭功能损害、听力损害）、肾毒性、神经肌肉阻滞。需监测血药浓度。",
            keywords: ["氨基糖苷", "链霉素", "庆大霉素", "耳毒性"],
          },
          {
            id: "DRUG-704",
            title: "四环素类抗生素",
            content: "四环素、多西环素、米诺环素。作用机制：抑制细菌蛋白质合成。",
            formula: "",
            mechanism: "作用机制：与细菌核糖体 30S 亚基结合，抑制氨酰-tRNA 进入 A 位，阻止蛋白质合成。",
            conditions: "影响骨骼和牙齿发育（与钙螯合），孕妇和 8 岁以下儿童禁用。",
            keywords: ["四环素", "多西环素", "蛋白质合成"],
          },
        ],
      },
      {
        chapter: "第十二章 合成抗菌药",
        sections: [
          {
            id: "DRUG-801",
            title: "喹诺酮类抗菌药",
            content: "诺氟沙星、环丙沙星、左氧氟沙星。作用机制：抑制 DNA 回旋酶。",
            formula: "",
            mechanism: "作用机制：抑制细菌 DNA 回旋酶（拓扑异构酶 II）和拓扑异构酶 IV，阻止 DNA 复制和转录。",
            conditions: "环丙沙星：革兰阴性菌活性强；左氧氟沙星：呼吸喹诺酮，非典型病原体有效。软骨损伤，孕妇和儿童禁用。",
            keywords: ["喹诺酮", "环丙沙星", "左氧氟沙星", "DNA回旋酶"],
            keywords: ["喹诺酮", "环丙沙星", "左氧氟沙星", "DNA回旋酶"],
          },
          {
            id: "DRUG-802",
            title: "磺胺类抗菌药",
            content: "磺胺甲恶唑、甲氧苄啶。作用机制：抑制叶酸合成。",
            keywords: ["磺胺", "叶酸", "抗菌"],
          },
        ],
      },
      {
        chapter: "第十四章 抗肿瘤药物",
        sections: [
          {
            id: "DRUG-901",
            title: "烷化剂",
            content: "环磷酰胺、氮芥。作用机制：与 DNA 共价结合，破坏 DNA 结构和功能。",
            formula: "",
            mechanism: "作用机制：烷化剂与 DNA 鸟嘌呤 N-7 位共价结合，形成交联，破坏 DNA 结构和功能，阻止肿瘤细胞分裂。",
            conditions: "环磷酰胺：需肝脏活化才产生活性；常见副作用：骨髓抑制、出血性膀胱炎。",
            keywords: ["烷化剂", "环磷酰胺", "氮芥", "DNA"],
          },
          {
            id: "DRUG-902",
            title: "抗代谢物",
            content: "甲氨蝶呤、氟尿嘧啶、阿糖胞苷。作用机制：干扰核酸合成。",
            formula: "",
            mechanism: "甲氨蝶呤：抑制二氢叶酸还原酶，阻止 DNA 合成；氟尿嘧啶：抑制胸苷酸合成酶；阿糖胞苷：抑制 DNA 聚合酶。",
            conditions: "甲氨蝶呤：儿童急性白血病；氟尿嘧啶：消化道肿瘤；阿糖胞苷：急性粒细胞白血病。",
            keywords: ["抗代谢物", "甲氨蝶呤", "氟尿嘧啶", "核酸合成"],
          },
          {
            id: "DRUG-903",
            title: "天然抗肿瘤药",
            content: "长春新碱、紫杉醇。作用机制：抑制微管蛋白聚合/解聚。",
            formula: "",
            mechanism: "长春新碱：抑制微管蛋白聚合，阻止纺锤体形成，细胞停留在 M 期；紫杉醇：抑制微管解聚，阻止细胞分裂。",
            conditions: "长春新碱：儿童急性淋巴细胞白血病；紫杉醇：卵巢癌、乳腺癌。神经毒性为主要副作用。",
            keywords: ["长春新碱", "紫杉醇", "微管"],
          },
        ],
      },
      {
        chapter: "第十五章 内分泌系统药物",
        sections: [
          {
            id: "DRUG-1001",
            title: "糖皮质激素",
            content: "氢化可的松、泼尼松、地塞米松。作用机制：与胞浆受体结合，调节基因转录。",
            formula: "",
            mechanism: "作用机制：进入细胞与糖皮质激素受体结合，进入细胞核调节基因转录，发挥抗炎、免疫抑制、抗毒、抗休克作用。",
            conditions: "氢化可的松：短效；泼尼松：中效；地塞米松：长效。长期使用可导致肾上腺皮质功能减退。",
            keywords: ["糖皮质激素", "氢化可的松", "地塞米松", "抗炎"],
          },
          {
            id: "DRUG-1002",
            title: "胰岛素及口服降糖药",
            content: "胰岛素、二甲双胍、磺酰脲类。临床：糖尿病治疗。",
            formula: "",
            mechanism: "胰岛素：促进葡萄糖摄取和利用，降低血糖；二甲双胍：减少肝糖输出，增加胰岛素敏感性；磺酰脲类：刺激胰岛β细胞分泌胰岛素。",
            conditions: "1型糖尿病：胰岛素替代治疗；2型糖尿病：口服降糖药，效果不佳时加用胰岛素。",
            keywords: ["胰岛素", "二甲双胍", "糖尿病", "降糖"],
          },
        ],
      },
      {
        chapter: "第十六章 维生素",
        sections: [
          {
            id: "DRUG-1101",
            title: "脂溶性维生素",
            content: "维生素A、D、E、K。脂溶性，可在体内储存。",
            formula: "",
            mechanism: "维生素A：视紫红质合成，维持视觉；维生素D：钙磷代谢，促进肠钙吸收；维生素E：抗氧化；维生素K：凝血因子合成。",
            conditions: "脂溶性维生素过量可中毒。维生素A缺乏：夜盲症；维生素D缺乏：佝偻病。",
            keywords: ["维生素", "脂溶性", "维生素A", "维生素D", "维生素E", "维生素K"],
          },
          {
            id: "DRUG-1102",
            title: "水溶性维生素",
            content: "维生素B族、维生素C。水溶性，过量随尿排出。",
            formula: "",
            mechanism: "维生素B1：糖代谢辅酶，缺乏→脚气病；维生素B2：生物氧化辅酶；维生素C：羟化反应，抗氧化，促进铁吸收。",
            conditions: "水溶性维生素过量一般不中毒。维生素C缺乏：坏血病。",
            keywords: ["维生素", "水溶性", "维生素B", "维生素C"],
          },
          {
            id: "DRUG-1103",
            title: "叶酸与维生素B12",
            content: "叶酸、维生素B12。与造血功能密切相关。",
            formula: "",
            mechanism: "叶酸：一碳单位载体，参与DNA合成。维生素B12：甲基丙二酰辅酶A变位酶辅酶，促进四氢叶酸再生。",
            conditions: "叶酸缺乏：巨幼红细胞性贫血。维生素B12缺乏：巨幼红细胞性贫血+神经系统损害。恶性贫血：内因子缺乏导致维生素B12吸收障碍。",
            keywords: ["叶酸", "维生素B12", "巨幼红细胞性贫血", "恶性贫血"],
          },
        ],
      },
      {
        chapter: "第十七章 抗组胺药",
        sections: [
          {
            id: "DRUG-1201",
            title: "H1受体拮抗剂",
            content: "苯海拉明、氯苯那敏、西替利嗪、氯雷他定。",
            formula: "",
            mechanism: "H1受体拮抗剂：阻断组胺与H1受体结合，抑制过敏反应。第一代（苯海拉明）易通过血脑屏障，嗜睡副作用明显。第二代（西替利嗪、氯雷他定）非镇静性。",
            conditions: "临床：过敏性鼻炎、荨麻疹、瘙痒。第一代：镇静、抗胆碱副作用；第二代：中枢副作用小。",
            keywords: ["抗组胺药", "H1受体", "苯海拉明", "氯雷他定"],
          },
          {
            id: "DRUG-1202",
            title: "H2受体拮抗剂",
            content: "西咪替丁、雷尼替丁、法莫替丁。",
            formula: "",
            mechanism: "H2受体拮抗剂：阻断胃壁细胞H2受体，抑制胃酸分泌。",
            conditions: "临床：消化性溃疡、胃食管反流病。西咪替丁：抗雄激素副作用；雷尼替丁：副作用少；法莫替丁：作用最强。",
            keywords: ["抗组胺药", "H2受体", "西咪替丁", "雷尼替丁"],
          },
        ],
      },
      {
        chapter: "第十八章 利尿药",
        sections: [
          {
            id: "DRUG-1301",
            title: "高效能利尿药",
            content: "呋塞米、依他尼酸。作用于髓袢升支粗段。",
            formula: "",
            mechanism: "抑制髓袢升支粗段Na⁺-K⁺-2Cl⁻同向转运体，减少NaCl重吸收，产生强大利尿作用。",
            conditions: "临床：急性肺水肿、脑水肿、急慢性肾功能衰竭。副作用：水电解质紊乱、耳毒性。",
            keywords: ["利尿药", "呋塞米", "髓袢利尿药", "水电解质紊乱"],
          },
          {
            id: "DRUG-1302",
            title: "中效能利尿药",
            content: "氢氯噻嗪。作用于远曲小管近端。",
            formula: "",
            mechanism: "抑制远曲小管近端Na⁺-Cl⁻同向转运体，减少NaCl重吸收。",
            conditions: "临床：高血压、尿崩症。副作用：高血糖、高血脂、高尿酸。",
            keywords: ["利尿药", "氢氯噻嗪", "噻嗪类", "高血压"],
          },
          {
            id: "DRUG-1303",
            title: "低效能利尿药",
            content: "螺内酯、氨苯蝶啶。保钾利尿药。",
            formula: "",
            mechanism: "螺内酯：竞争性拮抗醛固酮受体；氨苯蝶啶：直接抑制远曲小管Na⁺通道。两者均减少K⁺排出。",
            conditions: "临床：与排钾利尿药合用，纠正低钾血症。螺内酯：保钾利尿，用于肝硬化腹水。",
            keywords: ["利尿药", "螺内酯", "保钾利尿药", "低钾血症"],
          },
        ],
      },
      {
        chapter: "第十九章 降血糖药",
        sections: [
          {
            id: "DRUG-1401",
            title: "胰岛素",
            content: "胰岛素：由胰岛β细胞分泌，降低血糖。",
            formula: "",
            mechanism: "胰岛素：促进葡萄糖摄取和利用，促进糖原合成，抑制糖异生。临床：1型糖尿病、2型糖尿病重度。",
            conditions: "胰岛素不良反应：低血糖、过敏反应、胰岛素抵抗。",
            keywords: ["降血糖药", "胰岛素", "糖尿病"],
          },
          {
            id: "DRUG-1402",
            title: "口服降血糖药",
            content: "磺酰脲类、双胍类、α-葡萄糖苷酶抑制剂、噻唑烷二酮类。",
            formula: "",
            mechanism: "磺酰脲类：刺激胰岛β细胞释放胰岛素；双胍类：减少肝糖输出；α-葡萄糖苷酶抑制剂：延缓碳水化合物吸收；噻唑烷二酮类：增加胰岛素敏感性。",
            conditions: "二甲双胍：2型糖尿病一线用药；阿卡波糖：餐后血糖控制。",
            keywords: ["降血糖药", "二甲双胍", "格列美脲", "阿卡波糖"],
          },
          {
            id: "DRUG-1403",
            title: "GLP-1受体激动剂",
            content: "艾塞那肽、利拉鲁肽。新型降糖药。",
            formula: "",
            mechanism: "GLP-1受体激动剂：葡萄糖依赖性促进胰岛素分泌，抑制胰高血糖素分泌，延缓胃排空，抑制食欲。",
            conditions: "临床：2型糖尿病，兼有减重效果。副作用：胃肠道反应（恶心、呕吐）。",
            keywords: ["GLP-1", "利拉鲁肽", "艾塞那肽", "减重"],
          },
        ],
      },
      {
        chapter: "第二十章 抗甲状腺药",
        sections: [
          {
            id: "DRUG-1501",
            title: "硫脲类",
            content: "甲硫氧嘧啶、丙硫氧嘧啶、甲巯咪唑。",
            formula: "",
            mechanism: "抑制甲状腺过氧化物酶，阻止甲状腺激素合成。丙硫氧嘧啶还抑制外周T4转化为T3。",
            conditions: "临床：甲亢内科治疗、术前准备、甲状腺危象。不良反应：过敏反应、粒细胞缺乏。",
            keywords: ["抗甲状腺药", "硫脲类", "丙硫氧嘧啶", "甲巯咪唑"],
          },
          {
            id: "DRUG-1502",
            title: "碘及碘化物",
            content: "复方碘溶液（卢戈液）。",
            formula: "",
            mechanism: "大剂量碘：抑制甲状腺激素释放，拮抗TSH作用。",
            conditions: "临床：甲亢术前准备、甲状腺危象。长期使用可诱发甲亢或甲减。",
            keywords: ["抗甲状腺药", "碘化物", "卢戈液"],
          },
        ],
      },
    ],
  },

  // ============================================================
  // 第三本: 药理学（第九版）- 杨宝峰
  // ============================================================
  "药理学（第九版）": {
    bookCode: "PHARM",
    totalChapters: 48,
    chapters: [
      {
        chapter: "第一章 药理学总论",
        sections: [
          {
            id: "PHARM-001",
            title: "药物效应动力学 (药效学)",
            content: "研究药物对机体的作用及作用机制。包括：药物作用、药理效应、治疗效果、不良反应。",
            formula: "",
            mechanism: "药效学核心：药物与受体结合 → 信号转导 → 细胞反应 → 器官效应 → 整体效应。治疗效果分为对因治疗和对症治疗。",
            conditions: "",
            keywords: ["药效学", "药物作用", "药理效应", "不良反应"],
          },
          {
            id: "PHARM-002",
            title: "药物代谢动力学 (药动学)",
            content: "研究机体对药物的作用。包括：吸收、分布、代谢、排泄。",
            formula: "",
            mechanism: "药动学核心：ADME 过程。吸收（Absorption）→ 分布（Distribution）→ 代谢（Metabolism）→ 排泄（Excretion）。",
            conditions: "",
            keywords: ["药动学", "吸收", "分布", "代谢", "排泄"],
          },
          {
            id: "PHARM-003",
            title: "不良反应分类",
            content: "1. 副反应 2. 毒性反应 3. 后遗效应 4. 停药反应 5. 变态反应 6. 特异质反应",
            formula: "",
            mechanism: "副反应：治疗剂量下出现的与治疗目的无关的作用；毒性反应：剂量过大或蓄积过多；后遗效应：停药后血药浓度已降至阈浓度以下残存的药理效应；停药反应：突然停药后原有疾病加剧。",
            conditions: "",
            keywords: ["不良反应", "副反应", "毒性反应", "变态反应"],
          },
          {
            id: "PHARM-004",
            title: "药物剂量与效应关系",
            content: "量效关系：药物剂量与效应的关系。",
            formula: "",
            mechanism: "量效曲线：最小有效量、最大效应（效能）、效价强度、半数有效量（ED50）、半数致死量（LD50）。治疗指数=LD50/ED50。",
            conditions: "治疗指数越大越安全。安全范围=LD5/ED95。",
            keywords: ["量效关系", "效能", "效价强度", "治疗指数"],
          },
        ],
      },
      {
        chapter: "第二章 药物代谢动力学",
        sections: [
          {
            id: "PHARM-101",
            title: "药物的吸收",
            content: "吸收：药物从给药部位进入血液循环的过程。给药途径：口服、舌下、直肠、吸入、注射、经皮。",
            formula: "",
            mechanism: "口服吸收：经胃肠道 → 门静脉 → 肝脏（首过效应）→ 体循环。首过效应大的药物生物利用度低。",
            conditions: "口服：方便但有首过效应；舌下/直肠：无首过效应；静脉注射：直接入血，无吸收过程。",
            keywords: ["吸收", "给药途径", "首过效应"],
          },
          {
            id: "PHARM-105",
            title: "药物消除动力学",
            content: "一级消除动力学、零级消除动力学。",
            formula: "",
            mechanism: "一级消除动力学：恒比消除，t1/2恒定，大多数药物。零级消除动力学：恒量消除，t1/2不恒定，如苯妥英钠、阿司匹林。",
            conditions: "半衰期（t1/2）：血药浓度下降一半所需时间。生物利用度（F）：药物进入体循环的速度和程度。",
            keywords: ["消除动力学", "半衰期", "生物利用度", "一级消除"],
          },
          {
            id: "PHARM-102",
            title: "药物的分布",
            content: "分布：药物从血循环到达机体各组织的过程。影响因素：血浆蛋白结合率、器官血流量、组织亲和力、屏障。",
            formula: "",
            mechanism: "药物与血浆蛋白结合后不能跨膜转运，暂时储存于血液中。血脑屏障：只允许脂溶性高、分子量小的药物通过。",
            conditions: "血浆蛋白结合率高的药物作用时间长；脂溶性高的药物易通过血脑屏障。",
            keywords: ["分布", "血浆蛋白结合", "血脑屏障"],
          },
          {
            id: "PHARM-103",
            title: "药物的代谢",
            content: "代谢：药物在体内发生化学结构改变的过程。主要器官：肝脏。酶系：细胞色素 P450 酶系。",
            formula: "",
            mechanism: "I 相反应：氧化、还原、水解，引入或暴露官能团；II 相反应：结合反应，与葡萄糖醛酸、硫酸等结合，增加水溶性。",
            conditions: "P450 酶诱导剂（如苯巴比妥）加速药物代谢；P450 酶抑制剂（如西咪替丁）减慢药物代谢。",
            keywords: ["代谢", "肝脏", "P450", "酶系"],
          },
          {
            id: "PHARM-104",
            title: "药物的排泄",
            content: "排泄：药物及其代谢产物排出体外的过程。主要器官：肾脏。其他：胆汁、乳汁、唾液、汗液。",
            formula: "",
            mechanism: "肾脏排泄：肾小球滤过 + 肾小管分泌 + 肾小管重吸收。酸化尿液可加速弱酸性药物排泄，碱化尿液可加速弱碱性药物排泄。",
            conditions: "肝功能不全时胆汁排泄减少；肾功能不全时经肾排泄的药物半衰期延长。",
            keywords: ["排泄", "肾脏", "胆汁", "乳汁"],
          },
        ],
      },
      {
        chapter: "第三章 药物效应动力学",
        sections: [
          {
            id: "PHARM-201",
            title: "受体理论",
            content: "受体：一类介导细胞信号转导的功能蛋白质。配体：能与受体特异性结合的物质。",
            formula: "",
            mechanism: "受体特性：特异性、饱和性、可逆性、高亲和力。激动药：既有亲和力又有内在活性；拮抗药：有亲和力无内在活性。",
            conditions: "",
            keywords: ["受体", "配体", "信号转导"],
          },
          {
            id: "PHARM-202",
            title: "激动药和拮抗药",
            content: "激动药：既有亲和力又有内在活性。拮抗药：有亲和力但无内在活性。部分激动药：内在活性不强。",
            formula: "",
            mechanism: "激动药（agonist）：与受体结合后产生药理效应，如肾上腺素激动β受体。拮抗药（antagonist）：与受体结合但不产生效应，如普萘洛尔阻断β受体。部分激动药：如喷他佐辛，低剂量激动，高剂量拮抗。",
            conditions: "",
            keywords: ["激动药", "拮抗药", "亲和力", "内在活性"],
          },
          {
            id: "PHARM-203",
            title: "受体类型",
            content: "1. G 蛋白偶联受体 (GPCR) 2. 离子通道受体 3. 酶活性受体 4. 细胞核激素受体",
            formula: "",
            mechanism: "GPCR：通过G蛋白介导信号转导，如肾上腺素受体；离子通道受体：配体门控离子通道，如N胆碱受体；酶活性受体：受体本身具有酶活性，如胰岛素受体；核受体：位于细胞核内，调节基因转录，如糖皮质激素受体。",
            conditions: "",
            keywords: ["GPCR", "离子通道", "酶活性受体", "核受体"],
          },
        ],
      },
      {
        chapter: "第四章 影响药物效应的因素",
        sections: [
          {
            id: "PHARM-301",
            title: "药物因素",
            content: "剂量、剂型、给药途径、反复用药、药物相互作用。",
            formula: "",
            mechanism: "剂量-效应关系：量反应、质反应。治疗指数（TI）= LD50/ED50，TI越大越安全。药物相互作用：协同作用、拮抗作用。",
            conditions: "首过效应：口服药物经肝脏代谢后进入体循环的药量减少。生物利用度（F）= 进入体循环的药量/给药剂量 × 100%。",
            keywords: ["药物因素", "剂量", "剂型", "药物相互作用", "治疗指数"],
          },
          {
            id: "PHARM-302",
            title: "机体因素",
            content: "年龄、性别、遗传、病理状态、心理因素。",
            formula: "",
            mechanism: "年龄：新生儿和老年人药物代谢排泄功能差。性别：女性对某些药物更敏感。遗传：药物代谢酶多态性（如CYP2D6超快代谢者/慢代谢者）。病理：肝肾功能不全影响药物代谢排泄。",
            conditions: "药物代谢酶多态性导致个体差异。首过效应明显的药物，肝功能不全时生物利用度增加。",
            keywords: ["机体因素", "年龄", "遗传", "病理状态"],
          },
          {
            id: "PHARM-303",
            title: "耐受性与耐药性",
            content: "耐受性：连续用药后机体对药物反应性降低。耐药性：病原体或肿瘤细胞对药物敏感性降低。",
            formula: "",
            mechanism: "耐受性：快速耐受性（如麻黄碱）、交叉耐受性。耐药性：细菌通过突变或获得耐药基因（如β-内酰胺酶）。",
            conditions: "耐受性：需要增加剂量才能达到原有效应。耐药性：药物治疗失败。",
            keywords: ["耐受性", "耐药性", "快速耐受", "交叉耐受"],
          },
        ],
      },
      {
        chapter: "第五章 传出神经系统药理",
        sections: [
          {
            id: "PHARM-401",
            title: "胆碱受体激动药",
            content: "毛果芸香碱、乙酰胆碱。",
            formula: "",
            mechanism: "M胆碱受体激动药：激动M受体，产生缩瞳、降低眼内压、调节痉挛。临床：青光眼。",
            conditions: "毛果芸香碱：青光眼首选，滴眼液。",
            keywords: ["传出神经", "胆碱受体", "毛果芸香碱", "青光眼"],
          },
          {
            id: "PHARM-402",
            title: "肾上腺素受体激动药",
            content: "肾上腺素、去甲肾上腺素、异丙肾上腺素、多巴胺。",
            formula: "",
            mechanism: "肾上腺素：α+β受体激动药，兴奋心脏、收缩血管、升高血压。去甲肾上腺素：α受体激动药。异丙肾上腺素：β受体激动药。",
            conditions: "肾上腺素：心脏骤停、过敏性休克；去甲肾上腺素：上消化道出血；异丙肾上腺素：支气管哮喘。",
            keywords: ["传出神经", "肾上腺素", "去甲肾上腺素", "异丙肾上腺素"],
          },
        ],
      },
      {
        chapter: "第六章 中枢神经系统药理",
        sections: [
          {
            id: "PHARM-501",
            title: "镇静催眠药",
            content: "苯二氮䓬类、巴比妥类。",
            formula: "",
            mechanism: "苯二氮䓬类：增强GABA与受体结合，增加Cl⁻通道开放频率。巴比妥类：延长Cl⁻通道开放时间。",
            conditions: "地西泮：抗焦虑、镇静催眠；苯巴比妥：抗癫痫。",
            keywords: ["中枢神经", "镇静催眠", "苯二氮䓬", "巴比妥"],
          },
          {
            id: "PHARM-502",
            title: "抗精神失常药",
            content: "抗精神病药、抗抑郁药、抗躁狂药。",
            formula: "",
            mechanism: "抗精神病药：阻断多巴胺受体；抗抑郁药：抑制单胺再摄取；抗躁狂药：碳酸锂。",
            conditions: "氯丙嗪：精神分裂症；氟西汀：抑郁症；碳酸锂：躁狂症。",
            keywords: ["中枢神经", "抗精神病", "抗抑郁", "氯丙嗪", "氟西汀"],
          },
        ],
      },
      {
        chapter: "第七章 心血管系统药理",
        sections: [
          {
            id: "PHARM-601",
            title: "抗高血压药",
            content: "利尿药、ACEI、ARB、β受体阻滞剂、钙通道阻滞剂。",
            formula: "",
            mechanism: "利尿药：减少血容量；ACEI：抑制ACE；ARB：阻断AT1受体；β受体阻滞剂：阻断β受体；CCB：阻断钙通道。",
            conditions: "一线降压药：ACEI/ARB、CCB、利尿剂。联合用药：ACEI+CCB、ACEI+利尿剂。",
            keywords: ["心血管", "高血压", "ACEI", "CCB", "利尿剂"],
          },
          {
            id: "PHARM-602",
            title: "抗心律失常药",
            content: "I类（钠通道阻滞剂）、II类（β受体阻滞剂）、III类（钾通道阻滞剂）、IV类（钙通道阻滞剂）。",
            formula: "",
            mechanism: "I类：阻滞钠通道（奎尼丁、利多卡因）；II类：β受体阻滞剂（普萘洛尔）；III类：延长动作电位时程（胺碘酮）；IV类：钙通道阻滞剂（维拉帕米）。",
            conditions: "利多卡因：室性心律失常；胺碘酮：广谱抗心律失常；维拉帕米：室上性心律失常。",
            keywords: ["心血管", "心律失常", "奎尼丁", "胺碘酮", "维拉帕米"],
          },
        ],
      },
      {
        chapter: "第八章 内脏系统药理",
        sections: [
          {
            id: "PHARM-701",
            title: "抗消化性溃疡药",
            content: "抗酸药、H2受体拮抗剂、质子泵抑制剂、胃黏膜保护药。",
            formula: "",
            mechanism: "H2受体拮抗剂：西咪替丁、雷尼替丁。质子泵抑制剂：奥美拉唑、兰索拉唑。胃黏膜保护药：硫糖铝、枸橼酸铋钾。",
            conditions: "奥美拉唑：溃疡病首选；枸橼酸铋钾：与抗生素合用根除Hp。",
            keywords: ["内脏", "消化性溃疡", "奥美拉唑", "H2受体拮抗剂"],
          },
          {
            id: "PHARM-702",
            title: "平喘药",
            content: "支气管扩张药、抗炎性平喘药。",
            formula: "",
            mechanism: "β2受体激动剂：沙丁胺醇、特布他林。茶碱类：氨茶碱。糖皮质激素：倍氯米松。抗过敏药：色甘酸钠。",
            conditions: "沙丁胺醇：急性发作；糖皮质激素：长期控制；色甘酸钠：预防发作。",
            keywords: ["内脏", "哮喘", "沙丁胺醇", "糖皮质激素"],
          },
        ],
      },
      {
        chapter: "第九章 内分泌系统药理",
        sections: [
          {
            id: "PHARM-801",
            title: "糖皮质激素",
            content: "可的松、氢化可的松、泼尼松、地塞米松。",
            formula: "",
            mechanism: "糖皮质激素：与胞浆受体结合→进入细胞核→调节基因转录。作用：抗炎、免疫抑制、抗毒素、抗休克。",
            conditions: "临床：严重感染、自身免疫病、过敏性疾病、休克。不良反应：类肾上腺皮质功能亢进症、诱发或加重感染、骨质疏松。",
            keywords: ["内分泌", "糖皮质激素", "可的松", "地塞米松"],
          },
          {
            id: "PHARM-802",
            title: "甲状腺激素",
            content: "甲状腺素（T4）、三碘甲状腺原氨酸（T3）。",
            formula: "",
            mechanism: "甲状腺激素：促进新陈代谢、生长发育、提高神经系统兴奋性。",
            conditions: "临床：呆小病、黏液性水肿。过量：甲亢症状。",
            keywords: ["内分泌", "甲状腺激素", "T3", "T4"],
          },
        ],
      },
      {
        chapter: "第十章 化疗药物",
        sections: [
          {
            id: "PHARM-901",
            title: "抗菌药物概述",
            content: "抗菌药：抑制或杀灭病原菌。",
            formula: "",
            mechanism: "抗菌机制：抑制细胞壁合成（青霉素）、影响细胞膜通透性（多粘菌素）、抑制蛋白质合成（氨基糖苷类）、抑制核酸合成（喹诺酮类）。",
            conditions: "抗菌谱：窄谱、广谱。耐药性：天然耐药、获得性耐药。",
            keywords: ["化疗药", "抗菌药", "抗菌谱", "耐药性"],
          },
          {
            id: "PHARM-902",
            title: "β-内酰胺类抗生素",
            content: "青霉素类、头孢菌素类。",
            formula: "",
            mechanism: "β-内酰胺类：与青霉素结合蛋白（PBPs）结合，抑制细胞壁肽聚糖合成。",
            conditions: "青霉素G：革兰阳性菌感染。头孢菌素：分四代，抗菌谱逐渐扩大。",
            keywords: ["化疗药", "青霉素", "头孢菌素", "β-内酰胺"],
          },
        ],
      },
      {
        chapter: "第十一章 抗恶性肿瘤药",
        sections: [
          {
            id: "PHARM-1001",
            title: "抗肿瘤药分类",
            content: "烷化剂、抗代谢药、抗肿瘤抗生素、抗肿瘤植物药。",
            formula: "",
            mechanism: "烷化剂：与DNA共价结合，破坏DNA结构。抗代谢药：干扰核酸合成。抗肿瘤抗生素：嵌入DNA，抑制RNA合成。抗肿瘤植物药：抑制微管蛋白。",
            conditions: "环磷酰胺：广谱抗肿瘤。甲氨蝶呤：叶酸拮抗剂。阿霉素：嵌入DNA。紫杉醇：抑制微管解聚。",
            keywords: ["抗肿瘤药", "烷化剂", "抗代谢药", "环磷酰胺", "紫杉醇"],
          },
          {
            id: "PHARM-1002",
            title: "抗肿瘤药不良反应",
            content: "骨髓抑制、消化道反应、脱发、肝肾功能损害。",
            formula: "",
            mechanism: "抗肿瘤药杀伤快速增殖细胞，包括正常骨髓细胞、消化道上皮细胞、毛囊细胞。",
            conditions: "骨髓抑制：白细胞下降、血小板下降。脱发：可逆。肝肾功能损害：需监测。",
            keywords: ["抗肿瘤药", "不良反应", "骨髓抑制", "脱发"],
          },
        ],
      },
      {
        chapter: "第十二章 免疫药理学",
        sections: [
          {
            id: "PHARM-1101",
            title: "免疫抑制药",
            content: "环孢素、他克莫司、糖皮质激素、环磷酰胺。",
            formula: "",
            mechanism: "环孢素：抑制钙调磷酸酶，抑制T细胞活化。他克莫司：类似环孢素，作用更强。糖皮质激素：广泛免疫抑制。环磷酰胺：细胞毒药物。",
            conditions: "临床：器官移植抗排斥、自身免疫病。环孢素：肾毒性、高血压。",
            keywords: ["免疫药理", "免疫抑制", "环孢素", "他克莫司"],
          },
          {
            id: "PHARM-1102",
            title: "免疫增强药",
            content: "左旋咪唑、转移因子、胸腺素、干扰素。",
            formula: "",
            mechanism: "左旋咪唑：恢复巨噬细胞功能。转移因子：传递细胞免疫信息。胸腺素：促进T细胞分化。干扰素：抗病毒、抗肿瘤。",
            conditions: "临床：免疫缺陷病、肿瘤辅助治疗、慢性感染。",
            keywords: ["免疫药理", "免疫增强", "左旋咪唑", "干扰素"],
          },
        ],
      },
    ],
  },

  // ============================================================
  // 第四本: 药物合成反应（第四版）- 闻韧
  // ============================================================
  "药物合成反应（第四版）": {
    bookCode: "SYNTH",
    totalChapters: 12,
    chapters: [
      {
        chapter: "第一章 卤化反应",
        sections: [
          {
            id: "SYNTH-001",
            title: "卤化反应概述",
            content: "卤化反应：在有机分子中引入卤素原子的反应。包括：不饱和烃的卤加成、饱和碳上的卤取代、芳香环上的卤取代。",
            formula: "",
            mechanism: "不饱和烃卤加成：亲电加成机理，卤素分子极化后进攻双键。饱和碳卤取代：自由基机理（光照）或亲核取代机理。芳香环卤取代：亲电取代机理。",
            conditions: "卤加成：CCl₄ 溶剂，低温；卤取代：光照或 FeBr₃ 催化。",
            keywords: ["卤化反应", "卤素", "卤加成", "卤取代"],
          },
          {
            id: "SYNTH-002",
            title: "芳香环卤代",
            content: "芳香环上的亲电卤代反应。",
            formula: "",
            mechanism: "芳香环卤代：亲电取代机理。Lewis酸催化（FeBr₃、AlCl₃）使卤素分子极化，产生亲电试剂X⁺。",
            conditions: "FeBr₃或AlCl₃催化，CCl₄溶剂。定位规则：邻对位定位基（-OH、-NH₂、-R），间位定位基（-NO₂、-COOH）。",
            keywords: ["芳香卤代", "亲电取代", "定位规则", "FeBr3"],
          },
        ],
      },
      {
        chapter: "第二章 烃化反应",
        sections: [
          {
            id: "SYNTH-101",
            title: "烃化反应概述",
            content: "烃化反应：在有机分子中引入烃基的反应。包括：C-烃化、N-烃化、O-烃化。",
            formula: "",
            mechanism: "C-烃化：Friedel-Crafts 反应，芳香环上引入烷基。N-烃化：胺与卤代烷反应。O-烃化：醇/酚与卤代烷反应生成醚。",
            conditions: "Friedel-Crafts：AlCl₃ 催化；N-烃化：碱催化；O-烃化：Williamson 合成，NaH 或 NaOH。",
            keywords: ["烃化反应", "C-烃化", "N-烃化", "O-烃化"],
          },
          {
            id: "SYNTH-102",
            title: "Friedel-Crafts 反应",
            content: "芳香环上的亲电取代反应，引入烷基或酰基。",
            formula: "",
            mechanism: "Friedel-Crafts 烷基化：芳烃 + 卤代烷/烯烃 + AlCl₃ → 烷基芳烃。Friedel-Crafts 酰基化：芳烃 + 酰卤/酸酐 + AlCl₃ → 芳酮。",
            conditions: "AlCl₃ 催化，CS₂ 或硝基苯溶剂。注意：烷基化易发生多烷基化和重排；酰基化不重排，产物单一。",
            keywords: ["Friedel-Crafts", "烷基化", "酰基化", "芳环", "亲电取代"],
          },
        ],
      },
      {
        chapter: "第五章 酰化反应",
        sections: [
          {
            id: "SYNTH-201",
            title: "酰化反应概述",
            content: "酰化反应：在有机分子中引入酰基的反应。包括：C-酰化、N-酰化、O-酰化。",
            formula: "",
            mechanism: "C-酰化：Friedel-Crafts 酰基化。N-酰化：胺与酰卤/酸酐反应生成酰胺。O-酰化：醇与酰卤/酸酐反应生成酯。",
            conditions: "Friedel-Crafts 酰基化：AlCl₃ 催化；N-酰化：吡啶或三乙胺；O-酰化：酯化反应，酸催化。",
            keywords: ["酰化反应", "酰基", "C-酰化", "N-酰化", "O-酰化"],
          },
          {
            id: "SYNTH-202",
            title: "阿司匹林的合成",
            content: "水杨酸 + 乙酸酐 → 阿司匹林 + 乙酸。催化剂：浓硫酸。反应条件：加热 80-90°C。",
            formula: "\\chemfig{*6(-COOH-OH-=-=-)} + (CH_3CO)_2O \\xrightarrow{H_2SO_4} \\chemfig{*6(-COOH-OCOCH_3-=-=-)} + CH_3COOH",
            mechanism: "酚羟基的 O-酰化反应。浓硫酸催化乙酸酐，与水杨酸的酚羟基反应生成乙酰水杨酸（阿司匹林）。羧基不反应。",
            conditions: "浓硫酸催化，加热 80-90°C，反应时间 30 分钟。",
            keywords: ["阿司匹林", "水杨酸", "乙酸酐", "酯化"],
          },
        ],
      },
      {
        chapter: "第六章 氧化反应",
        sections: [
          {
            id: "SYNTH-301",
            title: "氧化反应概述",
            content: "氧化反应：有机分子中加氧或去氢的反应。包括：醇氧化、醛氧化、烃氧化。",
            formula: "",
            mechanism: "醇氧化：伯醇→醛→羧酸，仲醇→酮，叔醇难氧化。常用氧化剂：KMnO₄、K₂Cr₂O₇、PCC、OsO₄。",
            conditions: "KMnO₄/K₂Cr₂O₇：强氧化，酸性条件；PCC：温和氧化，伯醇停在醛。",
            keywords: ["氧化反应", "醇氧化", "醛氧化", "氧化剂"],
          },
          {
            id: "SYNTH-302",
            title: "药物合成中的氧化反应",
            content: "1. 羟基氧化：醇→醛/酮 2. 脱氢：醇→醛/酮 3. 芳烃氧化：苯→苯酚",
            formula: "",
            mechanism: "在药物合成中，氧化反应用于引入含氧官能团。如：可的松合成中的羟基氧化。",
            conditions: "根据底物选择温和氧化剂，避免过度氧化。",
            keywords: ["药物合成", "氧化反应", "羟基氧化"],
          },
          {
            id: "SYNTH-303",
            title: "Baeyer-Villiger氧化",
            content: "酮→酯/内酯。过氧酸氧化。",
            formula: "",
            mechanism: "酮与过氧酸（m-CPBA）反应，氧原子插入羰基与α-碳之间，生成酯或内酯。迁移倾向：叔烷基>仲烷基>芳基>伯烷基>甲基。",
            conditions: "常用过氧酸：m-CPBA、过氧乙酸。CH₂Cl₂溶剂，室温。",
            keywords: ["Baeyer-Villiger", "酮", "酯", "过氧酸"],
          },
        ],
      },
      {
        chapter: "第七章 还原反应",
        sections: [
          {
            id: "SYNTH-401",
            title: "还原反应概述",
            content: "还原反应：有机分子中加氢或去氧的反应。包括：催化加氢、化学还原。",
            formula: "",
            mechanism: "催化加氢：H₂/Pd、H₂/Pt、H₂/Ni。化学还原：NaBH₄、LiAlH₄、Clemmensen 还原。",
            conditions: "NaBH₄：温和，只还原醛酮；LiAlH₄：强，还原醛酮羧酸酯；Clemmensen：Zn-Hg/HCl，羰基→亚甲基。",
            keywords: ["还原反应", "催化加氢", "NaBH4", "LiAlH4"],
          },
          {
            id: "SYNTH-402",
            title: "选择性还原",
            content: "选择性还原：控制反应条件，只还原特定官能团。",
            formula: "",
            mechanism: "NaBH₄：只还原醛酮，不还原酯、羧酸、酰胺。LiAlH₄：还原醛酮、羧酸、酯、酰胺。催化加氢：双键>三键>芳环。",
            conditions: "Lindlar催化剂：炔烃→顺式烯烃。Rosenmund还原：酰氯→醛。Wolff-Kishner还原：羰基→亚甲基。",
            keywords: ["选择性还原", "NaBH4", "Lindlar", "Rosenmund"],
          },
        ],
      },
      {
        chapter: "第八章 重排反应",
        sections: [
          {
            id: "SYNTH-501",
            title: "重排反应概述",
            content: "重排反应：分子内原子或基团重新排列的反应。",
            formula: "",
            mechanism: "常见重排：Wagner-Meerwein重排（碳正离子重排）、Beckmann重排（肟→酰胺）、Hofmann重排（酰胺→胺）。",
            conditions: "Wagner-Meerwein：酸催化；Beckmann：酸催化（PCl₅）；Hofmann：Br₂/NaOH。",
            keywords: ["重排反应", "Wagner-Meerwein", "Beckmann", "Hofmann"],
          },
          {
            id: "SYNTH-502",
            title: "Claisen重排",
            content: "烯丙基芳基醚→邻烯丙基苯酚。[3,3]σ迁移。",
            formula: "",
            mechanism: "Claisen重排：协同反应，[3,3]-σ迁移。烯丙基芳基醚加热到200°C，生成邻烯丙基苯酚。",
            conditions: "加热（200°C），协同反应。是制备酚类化合物的重要方法。",
            keywords: ["Claisen重排", "烯丙基", "苯酚", "σ迁移"],
          },
        ],
      },
      {
        chapter: "第九章 环合反应",
        sections: [
          {
            id: "SYNTH-601",
            title: "环合反应概述",
            content: "环合反应：形成环状化合物的反应。",
            formula: "",
            mechanism: "常见环合：Diels-Alder反应（[4+2]环加成）、Friedel-Crafts环合、分子内亲核取代环合。",
            conditions: "Diels-Alder：加热，协同反应；Friedel-Crafts：AlCl₃催化。",
            keywords: ["环合反应", "Diels-Alder", "环加成", "成环"],
          },
          {
            id: "SYNTH-602",
            title: "杂环化合物合成",
            content: "杂环化合物：含杂原子的环状化合物。",
            formula: "",
            mechanism: "常见杂环合成：Paal-Knorr合成吡咯、Fischer吲哚合成、Hantzsch吡啶合成。",
            conditions: "Paal-Knorr：1,4-二酮+胺；Fischer：苯肼+酮；Hantzsch：β-酮酯+醛+氨。",
            keywords: ["杂环", "Paal-Knorr", "Fischer吲哚", "Hantzsch"],
          },
        ],
      },
      {
        chapter: "第十章 催化反应",
        sections: [
          {
            id: "SYNTH-701",
            title: "催化氢化反应",
            content: "催化加氢：H₂/Pd、H₂/Pt、H₂/Ni。",
            formula: "",
            mechanism: "多相催化：吸附→活化→反应→解吸。选择性：双键>三键>芳环。",
            conditions: "Pd/C：最常用，活性高；Ni：Raney Ni，活性中等；Pt：活性最高，价格贵。",
            keywords: ["催化反应", "催化氢化", "Pd/C", "加氢"],
          },
          {
            id: "SYNTH-703",
            title: "不对称催化",
            content: "不对称催化：手性催化剂诱导产生单一对映体。",
            formula: "",
            mechanism: "手性配体：BINAP、DIOP。金属：Rh、Ru、Ir。不对称氢化、不对称环氧化（Sharpless）。",
            conditions: "Sharpless不对称环氧化：Ti(OiPr)₄+酒石酸二乙酯+TBHP。Sharpless不对称双羟基化：OsO₄+手性配体。",
            keywords: ["不对称催化", "手性", "BINAP", "Sharpless"],
          },
          {
            id: "SYNTH-702",
            title: "相转移催化",
            content: "相转移催化剂（PTC）：季铵盐、冠醚。",
            formula: "",
            mechanism: "PTC将水相中的反应物转移到有机相，加速反应。不需要无水条件，操作简便。",
            conditions: "常用PTC：四丁基溴化铵（TBAB）、三乙基苄基氯化铵（TEBA）、18-冠-6。",
            keywords: ["相转移催化", "PTC", "季铵盐", "冠醚"],
          },
        ],
      },
      {
        chapter: "第十一章 拆分与消旋",
        sections: [
          {
            id: "SYNTH-801",
            title: "外消旋体拆分",
            content: "拆分：将外消旋体分离为单一异构体。方法：化学拆分、酶拆分、色谱拆分。",
            formula: "",
            mechanism: "化学拆分：利用手性试剂与外消旋体生成非对映异构体，利用溶解度差异分离。酶拆分：利用酶的立体专一性。色谱拆分：手性色谱柱。",
            conditions: "化学拆分：经典方法，收率低（理论50%）。酶拆分：高效，选择性好。色谱拆分：适用于分析。",
            keywords: ["拆分", "外消旋体", "手性", "对映异构体"],
          },
          {
            id: "SYNTH-802",
            title: "消旋化",
            content: "消旋化：将单一异构体转化为外消旋体。",
            formula: "",
            mechanism: "通过反应使手性中心构型翻转或消失。常见：酸催化消旋、碱催化消旋、热消旋。",
            conditions: "酸催化：通过烯醇化或碳正离子中间体。碱催化：通过烯醇负离子。",
            keywords: ["消旋化", "构型翻转", "外消旋化"],
          },
        ],
      },
      {
        chapter: "第十二章 药物合成路线设计",
        sections: [
          {
            id: "SYNTH-901",
            title: "逆合成分析",
            content: "逆合成分析：从目标分子反向推导合成路线。",
            formula: "",
            mechanism: "逆合成：目标分子→前体→原料。关键反应：官能团转化（FGI）、官能团添加（FGA）、官能团消除（FGR）。",
            conditions: "常用切断：C-C键、C-X键。合成子：接受体、给予体。",
            keywords: ["逆合成", "合成路线", "切断", "合成子"],
          },
          {
            id: "SYNTH-902",
            title: "药物合成路线评价",
            content: "评价标准：收率、成本、环保、安全。",
            formula: "",
            mechanism: "评价维度：总收率、步骤数、原料成本、三废处理、安全生产。绿色化学原则：原子经济性、减少副产物。",
            conditions: "理想路线：步骤少、收率高、原料易得、环境友好。",
            keywords: ["合成路线", "评价", "绿色化学", "原子经济性"],
          },
          {
            id: "SYNTH-903",
            title: "手性药物合成策略",
            content: "手性药物：单一对映体。合成策略：手性池合成、不对称合成、不对称催化。",
            formula: "",
            mechanism: "手性池合成：从天然手性原料出发（氨基酸、糖）。不对称合成：使用手性催化剂或手性辅基。外消旋体拆分：化学拆分或酶拆分。",
            conditions: "手性药物要求单一对映体，避免对映体副作用。如：沙利度胺事件（R-止吐，S-致畸）。",
            keywords: ["手性药物", "手性池", "不对称合成", "沙利度胺"],
          },
        ],
      },
    ],
  },

  // ============================================================
  // 第五本: 生物化学与分子生物学（第10版）- 高国全
  // ============================================================
  "生物化学与分子生物学（第10版）": {
    bookCode: "BIO",
    totalChapters: 26,
    chapters: [
      {
        chapter: "第一章 蛋白质的结构与功能",
        sections: [
          {
            id: "BIO-001",
            title: "氨基酸",
            content: "蛋白质的基本组成单位。20 种标准氨基酸。分类：非极性、极性中性、酸性、碱性。",
            formula: "",
            mechanism: "氨基酸通过肽键连接形成多肽链。肽键：-CO-NH-，具有部分双键性质，不能自由旋转。",
            conditions: "",
            keywords: ["氨基酸", "蛋白质", "20种氨基酸"],
          },
          {
            id: "BIO-002",
            title: "蛋白质的分子结构",
            content: "一级结构：氨基酸序列。二级结构：α-螺旋、β-折叠。三级结构：整条肽链的空间排布。四级结构：亚基的聚合。",
            formula: "",
            mechanism: "一级结构：肽键连接；二级结构：氢键维持 α-螺旋和 β-折叠；三级结构：疏水键、氢键、盐键、二硫键维持；四级结构：亚基间非共价键。",
            conditions: "",
            keywords: ["蛋白质结构", "一级", "二级", "三级", "四级", "α-螺旋", "β-折叠"],
          },
        ],
      },
      {
        chapter: "第六章 糖代谢",
        sections: [
          {
            id: "BIO-101",
            title: "糖酵解途径 (EMP)",
            content: "葡萄糖 → 2 丙酮酸。净生成 2 ATP + 2 NADH。关键酶：己糖激酶、磷酸果糖激酶-1、丙酮酸激酶。",
            formula: "\\chemfig{C_6H_{12}O_6} + 2 NAD^+ + 2 ADP + 2 Pi \\to 2 \\chemfig{CH_3COCOOH} + 2 NADH + 2 H^+ + 2 ATP + 2 H_2O",
            mechanism: "糖酵解分两个阶段：投资阶段（消耗 2 ATP）和收益阶段（产生 4 ATP）。关键酶：磷酸果糖激酶-1 是限速酶。",
            conditions: "胞液中进行，无需氧。缺氧时丙酮酸还原为乳酸。",
            keywords: ["糖酵解", "EMP", "丙酮酸", "ATP", "关键酶"],
          },
          {
            id: "BIO-102",
            title: "三羧酸循环 (TCA)",
            content: "乙酰 CoA → CO2 + H2O。在线粒体进行。关键酶：柠檬酸合酶、异柠檬酸脱氢酶、α-酮戊二酸脱氢酶。",
            formula: "",
            mechanism: "乙酰 CoA 与草酰乙酸缩合生成柠檬酸，经过 8 步反应，最终生成 2 CO₂、3 NADH、1 FADH₂、1 GTP。NADH 和 FADH₂ 进入呼吸链产生 ATP。",
            conditions: "线粒体基质中进行，需氧。是糖、脂肪、蛋白质三大物质代谢的最终通路。",
            keywords: ["三羧酸循环", "TCA", "乙酰CoA", "线粒体"],
          },
          {
            id: "BIO-103",
            title: "磷酸戊糖途径",
            content: "葡萄糖 → 核糖 + NADPH。意义：提供 NADPH 和核糖。",
            formula: "",
            mechanism: "分为氧化阶段和非氧化阶段。氧化阶段：葡萄糖-6-磷酸 → 核酮糖-5-磷酸，生成 2 NADPH 和 CO₂。非氧化阶段：戊糖磷酸互相转化。",
            conditions: "胞液中进行。NADPH 用于合成代谢和抗氧化。",
            keywords: ["磷酸戊糖途径", "NADPH", "核糖"],
          },
        ],
      },
      {
        chapter: "第七章 脂代谢",
        sections: [
          {
            id: "BIO-201",
            title: "脂肪酸的β-氧化",
            content: "脂肪酸 → 乙酰 CoA + FADH₂ + NADH。在线粒体进行。",
            formula: "",
            mechanism: "β-氧化分四步：脱氢（FADH₂）、加水、再脱氢（NADH）、硫解。每轮切下一个乙酰 CoA。",
            conditions: "线粒体基质中进行，需肉碱转运。16碳软脂酸经7轮β-氧化生成8个乙酰CoA。",
            keywords: ["脂肪酸", "β-氧化", "乙酰CoA", "线粒体"],
          },
          {
            id: "BIO-202",
            title: "酮体代谢",
            content: "酮体：乙酰乙酸、β-羟丁酸、丙酮。肝脏生成，肝外利用。",
            formula: "",
            mechanism: "饥饿或糖尿病时，脂肪酸大量β-氧化生成乙酰 CoA，乙酰 CoA 在肝脏缩合生成酮体。酮体通过血液运输到脑、肌肉等肝外组织氧化供能。",
            conditions: "肝脏是生成酮体的器官，但不能利用酮体。长期饥饿或糖尿病时酮体堆积导致酮症酸中毒。",
            keywords: ["酮体", "乙酰乙酸", "β-羟丁酸", "丙酮", "酮症酸中毒"],
          },
        ],
      },
      {
        chapter: "第八章 氨基酸代谢",
        sections: [
          {
            id: "BIO-301",
            title: "氨基酸的脱氨基作用",
            content: "转氨基作用、氧化脱氨基、联合脱氨基。",
            formula: "",
            mechanism: "转氨基：氨基转移到α-酮戊二酸生成谷氨酸；氧化脱氨基：谷氨酸在谷氨酸脱氢酶作用下生成α-酮戊二酸和氨；联合脱氨基：转氨基+氧化脱氨基。",
            conditions: "联合脱氨基是体内最主要的脱氨基方式。氨主要在肝脏合成尿素排出。",
            keywords: ["脱氨基", "转氨基", "氧化脱氨基", "尿素循环"],
          },
          {
            id: "BIO-302",
            title: "尿素循环",
            content: "氨 + CO₂ → 尿素。在肝脏进行。",
            formula: "",
            mechanism: "尿素循环分五步：氨甲酰磷酸合成 → 瓜氨酸 → 精氨酸代琥珀酸 → 精氨酸 → 尿素。每循环消耗4个高能磷酸键。",
            conditions: "肝脏是尿素合成的主要器官。肝功能严重损伤时尿素合成障碍，血氨升高，导致肝性脑病。",
            keywords: ["尿素循环", "氨", "尿素", "肝脏", "肝性脑病"],
          },
          {
            id: "BIO-303",
            title: "一碳单位代谢",
            content: "一碳单位：甲基、甲烯基、甲炔基、甲酰基。",
            formula: "",
            mechanism: "一碳单位代谢：四氢叶酸（FH₄）是载体。一碳单位来自丝氨酸、甘氨酸、组氨酸。",
            conditions: "一碳单位功能：参与嘌呤、嘧啶合成。叶酸缺乏导致一碳单位代谢障碍，巨幼红细胞性贫血。",
            keywords: ["一碳单位", "四氢叶酸", "叶酸", "巨幼红细胞性贫血"],
          },
        ],
      },
      {
        chapter: "第十章 DNA的生物合成",
        sections: [
          {
            id: "BIO-401",
            title: "DNA复制",
            content: "DNA → DNA。半保留复制。需要：模板、原料、酶。",
            formula: "",
            mechanism: "半保留复制：DNA双链解开，每条链作为模板合成新链。关键酶：DNA聚合酶、解旋酶、引物酶、连接酶。",
            conditions: "原核生物：DNA聚合酶I/II/III；真核生物：DNA聚合酶α/β/γ/δ/ε。",
            keywords: ["DNA复制", "半保留复制", "DNA聚合酶", "中心法则"],
          },
          {
            id: "BIO-402",
            title: "逆转录",
            content: "RNA → DNA。逆转录酶催化。",
            formula: "",
            mechanism: "逆转录：以RNA为模板合成DNA。逆转录酶具有三种活性：RNA指导的DNA聚合酶、RNA酶H、DNA指导的DNA聚合酶。",
            conditions: "逆转录病毒（如HIV）感染宿主细胞时发生。是分子生物学研究的重要工具。",
            keywords: ["逆转录", "RNA", "逆转录酶", "HIV"],
          },
          {
            id: "BIO-403",
            title: "DNA损伤与修复",
            content: "DNA损伤：突变、损伤。修复：光修复、切除修复、重组修复。",
            formula: "",
            mechanism: "DNA损伤：紫外线→胸腺嘧啶二聚体、化学诱变→碱基修饰。修复方式：光修复酶直接修复、切除修复（核苷酸切除/碱基切除）、重组修复（SOS修复）。",
            conditions: "切除修复是最主要的修复方式。修复缺陷导致遗传病（如着色性干皮病）和肿瘤。",
            keywords: ["DNA损伤", "DNA修复", "切除修复", "突变"],
          },
        ],
      },
      {
        chapter: "第十一章 RNA的生物合成",
        sections: [
          {
            id: "BIO-501",
            title: "转录",
            content: "DNA → RNA。RNA聚合酶催化。",
            formula: "",
            mechanism: "转录分三步：起始（RNA聚合酶结合启动子）、延伸（RNA链延长）、终止（RNA聚合酶脱落）。",
            conditions: "原核生物：一种RNA聚合酶；真核生物：三种RNA聚合酶（I/II/III）。",
            keywords: ["转录", "RNA聚合酶", "启动子", "终止子"],
          },
          {
            id: "BIO-502",
            title: "RNA转录后加工",
            content: "真核生物mRNA转录后加工：5'帽、3'polyA尾、剪接。",
            formula: "",
            mechanism: "5'帽：7-甲基鸟苷酸帽。3'polyA尾：多聚腺苷酸尾。剪接：去除内含子，连接外显子。",
            conditions: "snRNP参与剪接过程。选择性剪接：同一基因产生不同mRNA，导致不同蛋白质。",
            keywords: ["RNA加工", "5'帽", "polyA尾", "剪接", "内含子"],
          },
        ],
      },
      {
        chapter: "第十二章 蛋白质的生物合成",
        sections: [
          {
            id: "BIO-601",
            title: "翻译",
            content: "mRNA → 蛋白质。核糖体催化。",
            formula: "",
            mechanism: "翻译分三步：起始（核糖体组装）、延伸（肽链延长）、终止（释放因子识别终止密码子）。遗传密码：mRNA上3个相邻碱基编码一个氨基酸。",
            conditions: "原核生物：70S核糖体；真核生物：80S核糖体。需要mRNA、tRNA、rRNA、氨基酸、能量。",
            keywords: ["翻译", "核糖体", "遗传密码", "mRNA", "tRNA"],
          },
        ],
      },
      {
        chapter: "第十三章 基因表达调控",
        sections: [
          {
            id: "BIO-701",
            title: "原核生物基因表达调控",
            content: "操纵子模型。乳糖操纵子、色氨酸操纵子。",
            formula: "",
            mechanism: "乳糖操纵子：阻遏蛋白+CAP正调控。色氨酸操纵子：阻遏蛋白+衰减子。",
            conditions: "原核生物基因表达调控主要在转录水平。",
            keywords: ["基因表达调控", "操纵子", "乳糖操纵子", "色氨酸操纵子"],
          },
          {
            id: "BIO-702",
            title: "真核生物基因表达调控",
            content: "染色质水平、转录水平、转录后水平、翻译水平、翻译后水平。",
            formula: "",
            mechanism: "染色质水平：DNA甲基化、组蛋白修饰。转录水平：转录因子（激活子/抑制子）、增强子。转录后水平：选择性剪接。翻译水平：mRNA稳定性。翻译后水平：蛋白质修饰。",
            conditions: "真核生物基因表达调控多层次。转录因子是关键调控元件。",
            keywords: ["真核生物", "基因表达调控", "转录因子", "增强子", "DNA甲基化"],
          },
        ],
      },
      {
        chapter: "第十四章 肝的生物化学",
        sections: [
          {
            id: "BIO-801",
            title: "肝在物质代谢中的作用",
            content: "肝是糖、脂、蛋白质代谢的中枢器官。",
            formula: "",
            mechanism: "肝：糖异生、尿素合成、酮体生成、胆汁酸合成、生物转化。肝功能严重损伤时，多种代谢紊乱。",
            conditions: "肝功能检查：ALT、AST、胆红素、白蛋白、凝血酶原时间。",
            keywords: ["肝", "生物化学", "糖异生", "尿素", "生物转化"],
          },
        ],
      },
      {
        chapter: "第十五章 血液生物化学",
        sections: [
          {
            id: "BIO-901",
            title: "血浆蛋白质",
            content: "血浆蛋白：白蛋白、球蛋白、纤维蛋白原。",
            formula: "",
            mechanism: "白蛋白：维持血浆胶体渗透压，运输营养物质；球蛋白：免疫功能；纤维蛋白原：凝血功能。",
            conditions: "白蛋白/球蛋白比值（A/G）：正常1.5-2.5。慢性肝病时A/G下降甚至倒置。",
            keywords: ["血液", "血浆蛋白", "白蛋白", "球蛋白"],
          },
          {
            id: "BIO-902",
            title: "血液凝固",
            content: "凝血因子：14种。凝血过程：外源性、内源性、共同通路。",
            formula: "",
            mechanism: "凝血三阶段：凝血酶原激活物形成→凝血酶形成→纤维蛋白形成。抗凝系统：抗凝血酶III、蛋白C系统。",
            conditions: "维生素K依赖的凝血因子：II、VII、IX、X。血友病：VIII因子缺乏（血友病A）、IX因子缺乏（血友病B）。",
            keywords: ["血液凝固", "凝血因子", "凝血酶", "纤维蛋白"],
          },
        ],
      },
      {
        chapter: "第十六章 维生素与微量元素",
        sections: [
          {
            id: "BIO-1001",
            title: "脂溶性维生素",
            content: "维生素A、D、E、K。",
            formula: "",
            mechanism: "维生素A：视觉、上皮分化；维生素D：钙磷代谢；维生素E：抗氧化；维生素K：凝血。",
            conditions: "维生素A缺乏：夜盲症、干眼病；维生素D缺乏：佝偻病（儿童）、骨软化症（成人）。",
            keywords: ["维生素", "脂溶性", "维生素A", "维生素D"],
          },
          {
            id: "BIO-1002",
            title: "水溶性维生素",
            content: "维生素B族、维生素C。",
            formula: "",
            mechanism: "维生素B1：TPP辅酶，缺乏→脚气病；维生素B2：FAD/FMN辅酶；维生素PP：NAD/NADP辅酶；维生素C：抗氧化、羟化。",
            conditions: "维生素C缺乏：坏血病。维生素B1缺乏：脚气病。",
            keywords: ["维生素", "水溶性", "维生素B", "维生素C"],
          },
          {
            id: "BIO-1003",
            title: "微量元素",
            content: "铁、锌、铜、硒、碘、氟。",
            formula: "",
            mechanism: "铁：血红蛋白、肌红蛋白、细胞色素。锌：多种酶的辅酶。铜：铜蓝蛋白、细胞色素氧化酶。硒：谷胱甘肽过氧化物酶。碘：甲状腺激素。",
            conditions: "铁缺乏：缺铁性贫血。碘缺乏：甲状腺肿大。锌缺乏：生长迟缓。",
            keywords: ["微量元素", "铁", "锌", "铜", "硒", "碘"],
          },
        ],
      },
      {
        chapter: "第十七章 代谢调节与整合",
        sections: [
          {
            id: "BIO-1101",
            title: "物质代谢的相互联系",
            content: "糖、脂、蛋白质代谢相互联系、相互转化。",
            formula: "",
            mechanism: "糖→脂：糖代谢产生的乙酰CoA可合成脂肪酸。脂→糖：甘油→糖异生，但脂肪酸不能净转化为糖。蛋白质→糖/脂：氨基酸脱氨基后进入糖代谢或脂代谢。",
            conditions: "三大代谢枢纽：乙酰CoA、丙酮酸、葡萄糖-6-磷酸。",
            keywords: ["代谢调节", "糖脂代谢", "蛋白质代谢", "代谢联系"],
          },
          {
            id: "BIO-1102",
            title: "饥饿时的代谢变化",
            content: "短期饥饿：糖原分解、糖异生、酮体生成。长期饥饿：酮体利用增加。",
            formula: "",
            mechanism: "短期饥饿（1-3天）：肝糖原耗尽，糖异生增强，脂肪动员增加，酮体生成。长期饥饿（>3天）：脑利用酮体，减少蛋白质分解。",
            conditions: "饥饿时胰岛素降低，胰高血糖素升高。",
            keywords: ["饥饿", "代谢变化", "糖异生", "酮体"],
          },
        ],
      },
      {
        chapter: "第十八章 水和电解质代谢",
        sections: [
          {
            id: "BIO-1201",
            title: "水和钠代谢",
            content: "水平衡：摄入=排出。钠平衡：肾调节。",
            formula: "",
            mechanism: "水平衡：饮水、食物水、代谢水；排出：肾、皮肤、肺、肠。钠平衡：肾小球滤过、肾小管重吸收。",
            conditions: "脱水：高渗性、等渗性、低渗性。水肿：钠水潴留。",
            keywords: ["水代谢", "钠代谢", "脱水", "水肿"],
          },
          {
            id: "BIO-1202",
            title: "钾代谢",
            content: "钾平衡：肾调节。",
            formula: "",
            mechanism: "钾是细胞内主要阳离子。98%在细胞内。血钾正常3.5-5.5mmol/L。醛固酮促进肾排钾。",
            conditions: "低钾血症（<3.5）：肌无力、心律失常。高钾血症（>5.5）：心律失常、心脏骤停。",
            keywords: ["钾代谢", "低钾血症", "高钾血症"],
          },
        ],
      },
      {
        chapter: "第十九章 酸碱平衡",
        sections: [
          {
            id: "BIO-1301",
            title: "酸碱平衡调节",
            content: "血液缓冲系统、肺调节、肾调节。",
            formula: "",
            mechanism: "血液缓冲：碳酸氢盐缓冲系统（最重要）、磷酸盐缓冲、血浆蛋白缓冲。肺调节：通过CO₂排出调节。肾调节：通过H⁺分泌和HCO₃⁻重吸收调节。",
            conditions: "血气分析：pH、PaCO₂、HCO₃⁻。酸中毒：pH<7.35；碱中毒：pH>7.45。",
            keywords: ["酸碱平衡", "缓冲系统", "血气分析", "酸中毒"],
          },
          {
            id: "BIO-1302",
            title: "酸碱平衡紊乱",
            content: "代谢性酸中毒、呼吸性酸中毒、代谢性碱中毒、呼吸性碱中毒。",
            formula: "",
            mechanism: "代谢性酸中毒：HCO₃⁻↓，pH↓。呼吸性酸中毒：PaCO₂↑，pH↓。代谢性碱中毒：HCO₃⁻↑，pH↑。呼吸性碱中毒：PaCO₂↓，pH↑。",
            conditions: "代偿：呼吸代偿代谢紊乱，肾代偿呼吸紊乱。代偿公式：预期PaCO₂=1.5×HCO₃⁻+8。",
            keywords: ["代谢性酸中毒", "呼吸性酸中毒", "代谢性碱中毒", "呼吸性碱中毒"],
          },
        ],
      },
      {
        chapter: "第二十章 癌基因与抑癌基因",
        sections: [
          {
            id: "BIO-1401",
            title: "癌基因",
            content: "癌基因：促进细胞增殖的基因。原癌基因：正常细胞中存在的癌基因同源序列。",
            formula: "",
            mechanism: "原癌基因：参与细胞增殖调控。突变后变为癌基因：Ras、Myc、Src。",
            conditions: "癌基因激活机制：点突变、基因扩增、染色体易位。",
            keywords: ["癌基因", "原癌基因", "Ras", "Myc"],
          },
          {
            id: "BIO-1402",
            title: "抑癌基因",
            content: "抑癌基因：抑制细胞增殖的基因。",
            formula: "",
            mechanism: "抑癌基因：p53、Rb、PTEN。p53：基因组卫士，DNA损伤时诱导凋亡。Rb：细胞周期检查点。",
            conditions: "抑癌基因失活：缺失、突变、甲基化。p53突变见于50%以上肿瘤。",
            keywords: ["抑癌基因", "p53", "Rb", "PTEN"],
          },
          {
            id: "BIO-1403",
            title: "肿瘤发生的分子机制",
            content: "肿瘤：多基因突变累积、多阶段发展。",
            formula: "",
            mechanism: "肿瘤发生：原癌基因激活+抑癌基因失活+DNA修复基因缺陷。Knudson二次突变假说：需要两次突变才能失活抑癌基因。",
            conditions: "肿瘤标志：AFP（肝癌）、CEA（结直肠癌）、PSA（前列腺癌）。肿瘤标志物用于筛查和监测。",
            keywords: ["肿瘤", "分子机制", "Knudson假说", "肿瘤标志"],
          },
        ],
      },
      {
        chapter: "第二十一章 基因诊断与基因治疗",
        sections: [
          {
            id: "BIO-1501",
            title: "基因诊断",
            content: "基因诊断：检测基因异常进行诊断。",
            formula: "",
            mechanism: "技术：PCR、DNA测序、基因芯片。应用：遗传病诊断、肿瘤诊断、感染性疾病诊断。",
            conditions: "PCR：最常用，快速灵敏。DNA测序：金标准。基因芯片：高通量。",
            keywords: ["基因诊断", "PCR", "DNA测序", "基因芯片"],
          },
          {
            id: "BIO-1502",
            title: "基因治疗",
            content: "基因治疗：将正常基因导入患者体内治疗疾病。",
            formula: "",
            mechanism: "策略：基因替代、基因修复、基因增强、基因失活。载体：病毒载体（逆转录病毒、腺病毒）、非病毒载体。",
            conditions: "临床应用：遗传病（ADA缺乏症）、肿瘤、心血管疾病。挑战：安全性、有效性、伦理。",
            keywords: ["基因治疗", "病毒载体", "基因替代"],
          },
          {
            id: "BIO-1503",
            title: "CRISPR-Cas9基因编辑",
            content: "CRISPR-Cas9：精准基因编辑技术。",
            formula: "",
            mechanism: "CRISPR-Cas9：sgRNA引导Cas9核酸酶切割DNA，通过同源重组修复或非同源末端连接实现基因编辑。",
            conditions: "应用：遗传病治疗、肿瘤治疗、农业育种。优势：精准、高效、简便。伦理问题：生殖系编辑。",
            keywords: ["CRISPR", "基因编辑", "Cas9", "sgRNA"],
          },
        ],
      },
    ],
  },
};

// 导出全局变量
// TEXTBOOK_KNOWLEDGE_BASE

// 挂载到全局对象
window.TEXTBOOK_KNOWLEDGE_BASE = TEXTBOOK_KNOWLEDGE_BASE;
