// ========== 完整教材知识库 (v17.2.0) ==========
// 索引编号系统:
// ORG-xxx: 有机化学（第六版）
// DRUG-xxx: 药物化学（第三版）
// PHARM-xxx: 药理学（第九版）
// SYNTH-xxx: 药物合成反应（第四版）
// BIO-xxx: 生物化学与分子生物学（第10版）

/**
 * 完整教材知识库
 * 每本教材按章节组织，知识点带唯一索引编号
 */
const TEXTBOOK_KNOWLEDGE_BASE = {
  // ============================================================
  // 第一本: 有机化学（第六版）- 天津大学
  // ============================================================
  "有机化学（第六版）": {
    bookCode: "ORG",
    totalChapters: 16,
    chapters: [
      {
        chapter: "第一章 绪论",
        sections: [
          {
            id: "ORG-001",
            title: "有机化合物和有机化学",
            content: "有机化合物是含碳化合物（碳氢化合物及其衍生物）。有机化学是研究有机化合物的来源、制备、结构、性质、应用以及有关理论的科学。",
            keywords: ["有机化合物", "有机化学", "碳氢化合物"],
          },
          {
            id: "ORG-002",
            title: "有机化合物的特点",
            content: "1. 可燃 2. 熔点低 3. 难溶于水 4. 反应速率慢 5. 反应产物复杂 6. 同分异构现象普遍",
            keywords: ["熔点", "溶解性", "同分异构"],
          },
          {
            id: "ORG-003",
            title: "有机化合物的结构",
            content: "凯库勒结构式、路易斯结构式、构造式。共价键的键长、键角、键能。",
            keywords: ["凯库勒", "路易斯", "共价键", "键长", "键角", "键能"],
          },
          {
            id: "ORG-004",
            title: "共价键的断裂方式",
            content: "1. 均裂：形成自由基，自由基反应 2. 异裂：形成离子，离子型反应",
            keywords: ["均裂", "异裂", "自由基", "离子型反应"],
          },
          {
            id: "ORG-005",
            title: "有机反应的类型",
            content: "1. 自由基反应 2. 离子型反应（亲电、亲核） 3. 协同反应",
            keywords: ["自由基反应", "亲电反应", "亲核反应", "协同反应"],
          },
        ],
      },
      {
        chapter: "第二章 烷烃",
        sections: [
          {
            id: "ORG-101",
            title: "烷烃的通式和同系列",
            content: "烷烃通式 CnH2n+2。同系列：具有同一通式、结构和性质相似、相互间相差一个或几个 CH2 的一系列化合物。",
            formula: "\\chemfig{C_nH_{2n+2}}",
            mechanism: "",
            conditions: "",
            keywords: ["通式", "同系列", "同系物", "CH2"],
          },
          {
            id: "ORG-102",
            title: "烷烃的命名",
            content: "1. 普通命名法：正、异、新 2. 系统命名法（IUPAC）：选主链、编号、写名称",
            formula: "",
            mechanism: "",
            conditions: "",
            keywords: ["普通命名", "系统命名", "IUPAC", "主链"],
          },
          {
            id: "ORG-103",
            title: "烷烃的结构",
            content: "sp3 杂化，四面体构型，键角 109.5°。σ 键：可以自由旋转。",
            formula: "",
            mechanism: "碳原子的 2s 和三个 2p 轨道杂化形成四个 sp³ 杂化轨道，指向正四面体的四个顶点。C-C σ 键：沿键轴方向头碰头重叠，可以自由旋转。",
            conditions: "",
            keywords: ["sp3杂化", "四面体", "σ键", "109.5°"],
          },
          {
            id: "ORG-104",
            title: "乙烷的构象",
            content: "交叉式和重叠式。交叉式能量最低，重叠式能量最高。纽曼投影式。",
            formula: "",
            mechanism: "交叉式：两个碳原子上的 C-H 键相距最远，排斥力最小，能量最低。重叠式：两个碳原子上的 C-H 键正对，排斥力最大，能量最高。",
            conditions: "",
            keywords: ["构象", "交叉式", "重叠式", "纽曼投影", "乙烷"],
          },
          {
            id: "ORG-105",
            title: "丁烷的构象",
            content: "对位交叉式（最稳定）、邻位交叉式、部分重叠式、全重叠式（最不稳定）。",
            formula: "",
            mechanism: "对位交叉式：两个甲基相距最远，空间位阻最小，能量最低。全重叠式：两个甲基正对，空间位阻最大，能量最高。",
            conditions: "",
            keywords: ["丁烷", "对位交叉", "邻位交叉", "重叠式"],
          },
          {
            id: "ORG-106",
            title: "烷烃的物理性质",
            content: "沸点：随分子量增加而升高，支链越多沸点越低。熔点：随分子量增加而升高，对称性高熔点高。",
            formula: "",
            mechanism: "",
            conditions: "状态：C1-C4 气体，C5-C16 液体，C17+ 固体。密度：随分子量增加而增大，但都小于水。",
            keywords: ["沸点", "熔点", "分子量", "支链"],
          },
          {
            id: "ORG-107",
            title: "烷烃的化学性质 - 卤代反应",
            content: "自由基卤代反应。链引发、链增长、链终止。活性：F2 > Cl2 > Br2 > I2。",
            formula: "\\chemfig{CH_4} + Cl_2 \\xrightarrow{光照} \\chemfig{CH_3Cl} + HCl",
            mechanism: "自由基链式反应：\n1. 链引发：Cl₂ → 2Cl·（光照）\n2. 链传递：Cl· + CH₄ → ·CH₃ + HCl；·CH₃ + Cl₂ → CH₃Cl + Cl·\n3. 链终止：自由基之间结合",
            conditions: "光照（紫外光）或加热（250-400°C）。氟代剧烈，氯代适中，溴代较慢，碘代不反应。",
            keywords: ["卤代反应", "自由基", "链引发", "链增长", "链终止"],
          },
          {
            id: "ORG-108",
            title: "烷烃的氧化反应",
            content: "燃烧生成 CO2 和 H2O，放出大量热。部分氧化生成醇、醛、酮等。",
            formula: "\\chemfig{CH_4} + 2O_2 \\xrightarrow{点燃} CO_2 + 2H_2O + 890 kJ/mol",
            mechanism: "",
            conditions: "点燃或催化剂。完全燃烧生成 CO₂ 和 H₂O；不完全燃烧生成 CO 或碳黑。",
            keywords: ["氧化", "燃烧", "CO2", "放热"],
          },
        ],
      },
      {
        chapter: "第三章 烯烃",
        sections: [
          {
            id: "ORG-201",
            title: "烯烃的结构",
            content: "sp2 杂化，平面构型，键角 ~120°。π 键：不能自由旋转。C=C 双键：一个 σ 键 + 一个 π 键。",
            keywords: ["sp2杂化", "π键", "双键", "120°"],
          },
          {
            id: "ORG-202",
            title: "烯烃的异构现象",
            content: "碳链异构、位置异构、顺反异构（几何异构）。顺反异构：双键两端各连不同基团。",
            keywords: ["顺反异构", "几何异构", "碳链异构", "位置异构"],
          },
          {
            id: "ORG-203",
            title: "烯烃的命名",
            content: "选含双键的最长碳链为主链，编号从靠近双键的一端开始。Z/E 命名法。",
            formula: "",
            mechanism: "",
            conditions: "",
            keywords: ["Z/E", "双键编号", "主链"],
          },
          {
            id: "ORG-204",
            title: "烯烃的亲电加成反应",
            content: "1. 加 HX：马氏规则 2. 加 H2O：酸催化，马氏规则 3. 加 X2：邻二卤代物 4. 加 HOX：卤代醇",
            formula: "\\chemfig{CH_2=CH_2} + Br_2 \\to \\chemfig{BrCH_2-CH_2Br}",
            mechanism: "第一步：亲电试剂（如 Br₂）极化，正电部分进攻双键，形成环正离子中间体（溴鎓离子）。第二步：亲核试剂从背面进攻，开环生成反式加成产物。",
            conditions: "加 HX：气体或浓水溶液；加 H₂O：酸催化（H₂SO₄）；加 X₂：CCl₄ 溶剂，室温；加 HOX：次卤酸水溶液。",
            keywords: ["亲电加成", "马氏规则", "HX", "H2O", "X2"],
          },
          {
            id: "ORG-205",
            title: "马氏规则",
            content: "不对称烯烃与不对称试剂加成时，试剂中的正性部分加在含氢较多的双键碳上。",
            formula: "\\chemfig{CH_3-CH=CH_2} + HBr \\to \\chemfig{CH_3-CHBr-CH_3} (主产物)",
            mechanism: "碳正离子中间体的稳定性：叔碳正离子 > 仲碳正离子 > 伯碳正离子。H⁺ 优先加到含氢较多的碳上，形成更稳定的碳正离子。",
            conditions: "无过氧化物存在时适用。",
            keywords: ["马氏规则", "不对称烯烃", "正性部分"],
          },
          {
            id: "ORG-206",
            title: "过氧化物效应",
            content: "在过氧化物存在下，HBr 加成遵循反马氏规则。自由基加成机制。",
            formula: "\\chemfig{CH_3-CH=CH_2} + HBr \\xrightarrow{ROOR} \\chemfig{CH_3-CH_2-CH_2Br} (主产物)",
            mechanism: "自由基加成：过氧化物分解产生自由基，引发 HBr 均裂生成 Br·，Br· 加到双键上形成更稳定的碳自由基。",
            conditions: "只有 HBr 有过氧化物效应，HCl 和 HI 没有。",
            keywords: ["过氧化物效应", "反马氏", "自由基", "HBr"],
          },
          {
            id: "ORG-207",
            title: "烯烃的氧化反应",
            content: "1. 催化氧化：环氧乙烷 2. 高锰酸钾氧化：邻二醇（冷稀）/ 断裂（加热） 3. 臭氧化：醛/酮",
            formula: "\\chemfig{CH_2=CH_2} \\xrightarrow{KMnO_4, H^+, \\Delta} CO_2 + H_2O",
            mechanism: "冷稀 KMnO₄：顺式加成，生成邻二醇。热浓 KMnO₄：双键断裂，生成羧酸或酮。臭氧化：生成臭氧化物，水解生成醛或酮。",
            conditions: "冷稀 KMnO₄：低温，中性或碱性；热浓 KMnO₄：加热，酸性；臭氧化：O₃，然后 Zn/H₂O。",
            keywords: ["氧化", "高锰酸钾", "臭氧化", "环氧乙烷"],
          },
          {
            id: "ORG-208",
            title: "烯烃的聚合反应",
            content: "加聚反应。乙烯 → 聚乙烯，丙烯 → 聚丙烯。",
            formula: "\\chemfig{n CH_2=CH_2} \\xrightarrow{催化剂} \\chemfig{(-CH_2-CH_2-)}_n",
            mechanism: "连锁聚合反应：引发剂产生活性中心（自由基或离子），引发单体加成，链增长，链终止。",
            conditions: "催化剂（Ziegler-Natta 或过氧化物），高温高压。",
            keywords: ["聚合", "加聚", "聚乙烯", "聚丙烯"],
          },
        ],
      },
      {
        chapter: "第四章 炔烃和二烯烃",
        sections: [
          {
            id: "ORG-301",
            title: "炔烃的结构",
            content: "sp 杂化，直线构型，键角 180°。C≡C 三键：一个 σ 键 + 两个 π 键。",
            keywords: ["sp杂化", "三键", "180°", "直线"],
          },
          {
            id: "ORG-302",
            title: "炔烃的加成反应",
            content: "1. 加 H2：先烯后烷 2. 加 X2：反式加成 3. 加 HX：马氏规则 4. 加 H2O：醛酮（互变异构）",
            keywords: ["炔烃", "加成", "互变异构", "炔醛"],
          },
          {
            id: "ORG-303",
            title: "炔烃的酸性",
            content: "端基炔氢有弱酸性（pKa ~25）。可与银氨溶液、亚铜氨溶液生成炔化物沉淀。",
            keywords: ["端基炔", "酸性", "银氨溶液", "炔化物"],
          },
          {
            id: "ORG-304",
            title: "二烯烃的分类",
            content: "1. 累积二烯烃 2. 孤立二烯烃 3. 共轭二烯烃",
            formula: "",
            mechanism: "",
            conditions: "",
            keywords: ["二烯烃", "共轭", "累积", "孤立"],
          },
          {
            id: "ORG-305",
            title: "共轭二烯烃的结构",
            content: "共轭效应：π 电子离域，键长平均化，体系能量降低。",
            formula: "\\chemfig{CH_2=CH-CH=CH_2}",
            mechanism: "四个碳原子均为 sp² 杂化，p 轨道侧面重叠形成连续的共轭体系。π 电子不再定域在两个碳原子之间，而是离域到整个共轭体系。",
            conditions: "",
            keywords: ["共轭效应", "离域", "键长平均化", "π电子"],
          },
          {
            id: "ORG-306",
            title: "共轭二烯烃的加成",
            content: "1,2-加成和 1,4-加成。低温以 1,2-加成为主，高温以 1,4-加成为主。",
            formula: "\\chemfig{CH_2=CH-CH=CH_2} + Br_2 \\to \\chemfig{BrCH_2-CH=CH-CH_2Br} (1,4-加成)",
            mechanism: "亲电加成：H⁺ 加到 C1 上，形成烯丙基碳正离子（共振杂化体），正电荷分布在 C2 和 C4 上。Br⁻ 可以进攻 C2（1,2-加成）或 C4（1,4-加成）。",
            conditions: "低温（-80°C）：动力学控制，1,2-加成为主；高温（40°C）：热力学控制，1,4-加成为主。",
            keywords: ["1,2-加成", "1,4-加成", "共轭加成"],
          },
          {
            id: "ORG-307",
            title: "Diels-Alder 反应",
            content: "共轭二烯烃与亲双烯体（烯烃/炔烃）反应生成环己烯。协同反应，顺式加成。",
            formula: "\\chemfig{CH_2=CH-CH=CH_2} + \\chemfig{CH_2=CH_2} \\to \\chemfig{*6(-=-=-=)}",
            mechanism: "协同反应：旧键断裂和新键形成同时进行，经过一个环状过渡态。顺式加成：亲双烯体的构型保持不变。",
            conditions: "加热，通常无催化剂。吸电子基团取代的亲双烯体反应更快。",
            keywords: ["Diels-Alder", "双烯合成", "协同反应", "环己烯"],
          },
        ],
      },
      {
        chapter: "第五章 脂环烃",
        sections: [
          {
            id: "ORG-401",
            title: "脂环烃的分类",
            content: "单环、多环（螺环、桥环）。环烷烃通式 CnH2n。",
            formula: "",
            mechanism: "",
            conditions: "",
            keywords: ["脂环烃", "单环", "螺环", "桥环"],
          },
          {
            id: "ORG-402",
            title: "环烷烃的命名",
            content: "单环：环某烷。取代基编号最小。桥环：桥头碳编号。",
            formula: "",
            mechanism: "",
            conditions: "",
            keywords: ["环烷烃", "命名", "桥头碳"],
          },
          {
            id: "ORG-403",
            title: "环烷烃的稳定性",
            content: "小环（3-4元）不稳定，中环（5-6元）稳定。拜尔张力学说。",
            formula: "",
            mechanism: "环张力来自角张力和扭转张力。小环中 sp³ 杂化碳的键角被迫偏离 109.5°，产生角张力。环丙烷 60°，环丁烷 90°，张力最大。",
            conditions: "环戊烷和环己烷键角接近 109.5°，张力最小，最稳定。",
            keywords: ["环张力", "拜尔学说", "稳定性"],
          },
          {
            id: "ORG-404",
            title: "环己烷的构象",
            content: "椅式（最稳定）、船式（不稳定）。直立键（a键）和平伏键（e键）。取代基优先在 e 键。",
            formula: "\\chemfig{*6(------)}",
            mechanism: "椅式构象中，所有 C-C 键角均为 109.5°，无角张力。相邻碳上的 C-H 键全为交叉式构象，无扭转张力。e 键取代基空间位阻小，比 a 键稳定。",
            conditions: "室温下，椅式构象占 99.9%。单取代环己烷中，e 键构象占优势。",
            keywords: ["环己烷", "椅式", "船式", "直立键", "平伏键"],
          },
        ],
      },
      {
        chapter: "第六章 对映异构",
        sections: [
          {
            id: "ORG-501",
            title: "偏振光和旋光性",
            content: "偏振光：只在一个平面振动的光。旋光性：使偏振光振动平面旋转的性质。",
            formula: "",
            mechanism: "尼科尔棱镜将自然光变为偏振光。手性分子使偏振光振动平面旋转。右旋（+）：顺时针；左旋（-）：逆时针。",
            conditions: "旋光度与温度、光源波长、溶液浓度、样品管长度有关。",
            keywords: ["偏振光", "旋光性", "右旋", "左旋"],
          },
          {
            id: "ORG-502",
            title: "手性和手性分子",
            content: "手性：物体与其镜像不能重合的性质。手性分子：与其镜像不能重合的分子。",
            formula: "",
            mechanism: "手性的本质：分子中没有对称面、对称中心或更迭对称轴。最常见的是手性碳原子（连有四个不同基团的 sp³ 碳）。",
            conditions: "",
            keywords: ["手性", "手性分子", "镜像", "重合"],
          },
          {
            id: "ORG-503",
            title: "手性碳和对映异构体",
            content: "手性碳：连有四个不同基团的碳原子。对映异构体：互为镜像但不重合的异构体。",
            formula: "",
            mechanism: "对映异构体物理性质相同（除旋光方向相反），化学性质在非手性环境中相同，在手性环境中不同（如与手性试剂反应、与酶结合）。",
            conditions: "",
            keywords: ["手性碳", "对映异构", "镜像"],
          },
          {
            id: "ORG-504",
            title: "Fischer 投影式",
            content: "横线代表向前，竖线代表向后。碳链竖直，氧化态高的在上。",
            formula: "",
            mechanism: "Fischer 投影式规则：1. 横线向前，竖线向后；2. 碳链竖直，氧化态高的碳在上；3. 不能离开纸面旋转；4. 可以在纸面内旋转 180°，不能旋转 90°。",
            conditions: "",
            keywords: ["Fischer", "投影式", "横线", "竖线"],
          },
          {
            id: "ORG-505",
            title: "R/S 构型标记",
            content: "1. 按次序规则排列基团 2. 最小基团放在最远 3. 观察 1→2→3 方向：顺时针 R，逆时针 S",
            formula: "",
            mechanism: "次序规则：1. 比较原子序数，大者优先；2. 双键/三键视为连接两个/三个相同原子；3. 同位素质量数大者优先。",
            conditions: "",
            keywords: ["R构型", "S构型", "次序规则", "标记"],
          },
          {
            id: "ORG-506",
            title: "含一个手性碳的化合物",
            content: "有一对对映异构体。外消旋体：等量对映体的混合物。",
            formula: "",
            mechanism: "外消旋体（±）无旋光性，因为左旋和右旋的旋光性相互抵消。外消旋体可以通过手性拆分（如手性色谱、成盐拆分）分离为纯对映体。",
            conditions: "",
            keywords: ["手性碳", "对映体", "外消旋体"],
          },
          {
            id: "ORG-507",
            title: "含两个手性碳的化合物",
            content: "1. 两个不同手性碳：4 个立体异构体（两对对映体） 2. 两个相同手性碳：3 个立体异构体（一对对映体 + 一个内消旋体）",
            formula: "",
            mechanism: "内消旋体（meso）：分子内有两个相同手性碳，但分子有对称面，旋光性内部抵消。内消旋体是纯净物，不是混合物。非对映体：不互为镜像的立体异构体。",
            conditions: "",
            keywords: ["两个手性碳", "内消旋体", "非对映体"],
          },
        ],
      },
      {
        chapter: "第七章 芳烃",
        sections: [
          {
            id: "ORG-601",
            title: "苯的结构",
            content: "sp2 杂化，平面正六边形，键角 120°。大 π 键：π 电子离域。",
            keywords: ["苯", "sp2杂化", "大π键", "离域", "正六边形"],
          },
          {
            id: "ORG-602",
            title: "苯的命名",
            content: "烷基苯：苯为母体。多取代苯：编号最小。邻(o-)、间(m-)、对(p-)。",
            keywords: ["苯", "命名", "邻位", "间位", "对位"],
          },
          {
            id: "ORG-603",
            title: "苯的亲电取代反应",
            content: "1. 卤代：苯 + Cl2/FeCl3 → 氯苯 2. 硝化：苯 + 浓HNO3/浓H2SO4 → 硝基苯 3. 磺化：苯 + 浓H2SO4 → 苯磺酸 4. Friedel-Crafts 反应：烷基化、酰基化",
            formula: "\\chemfig{*6(-=-=-=)} + Br_2 \\xrightarrow{FeBr_3} \\chemfig{*6(-=-=-Br-)} + HBr",
            mechanism: "亲电取代机理：1. 亲电试剂（如 Br⁺）进攻苯环，形成 σ 络合物（碳正离子中间体）；2. σ 络合物脱去质子，恢复芳香性。",
            conditions: "卤代：FeBr₃/FeCl₃ 催化；硝化：浓 HNO₃ + 浓 H₂SO₄，50-60°C；磺化：发烟 H₂SO₄，加热；Friedel-Crafts：AlCl₃ 催化。",
            keywords: ["亲电取代", "卤代", "硝化", "磺化", "Friedel-Crafts"],
          },
          {
            id: "ORG-604",
            title: "亲电取代反应历程",
            content: "1. 亲电试剂进攻，形成 σ 络合物（碳正离子中间体） 2. 脱去质子，恢复芳香性",
            formula: "",
            mechanism: "第一步：亲电试剂进攻苯环，形成非芳香性的 σ 络合物（碳正离子中间体），这是决速步。第二步：脱去质子，恢复芳香性，生成产物。",
            conditions: "",
            keywords: ["亲电取代", "σ络合物", "碳正离子", "中间体"],
          },
          {
            id: "ORG-605",
            title: "定位效应",
            content: "邻对位定位基（第一类）：-NH2, -OH, -OR, -R, -X 间位定位基（第二类）：-NO2, -CN, -SO3H, -CHO, -COOH",
            formula: "",
            mechanism: "邻对位定位基：给电子基团，使苯环电子云密度增加，活化苯环，新取代基进入邻位和对位。间位定位基：吸电子基团，使苯环电子云密度降低，钝化苯环，新取代基进入间位。",
            conditions: "",
            keywords: ["定位效应", "邻对位", "间位", "定位基"],
          },
          {
            id: "ORG-606",
            title: "苯的侧链反应",
            content: "1. 侧链氧化：烷基苯 + KMnO4 → 苯甲酸 2. 侧链卤代：光照下 α-卤代",
            formula: "\\chemfig{*6(-=-=-CH_3-)} \\xrightarrow{KMnO_4, H^+, \\Delta} \\chemfig{*6(-=-=-COOH-)}",
            mechanism: "侧链氧化：无论侧链长短，只要有 α-H，最终都氧化为苯甲酸。侧链卤代：自由基机理，光照下 α-H 被卤素取代。",
            conditions: "氧化：KMnO₄/K₂Cr₂O₇，酸性，加热；卤代：光照，Cl₂/Br₂。",
            keywords: ["侧链氧化", "侧链卤代", "烷基苯"],
          },
          {
            id: "ORG-607",
            title: "稠环芳烃",
            content: "萘、蒽、菲。萘的亲电取代：α 位活性高。",
            formula: "\\chemfig{*6(-=-=-=*6(=-=-=-))}",
            mechanism: "萘的 α 位电子云密度比 β 位高，亲电取代优先发生在 α 位。蒽和菲的亲电取代优先发生在 9,10 位。",
            conditions: "萘的硝化：低温，主要 α-硝基萘；磺化：低温 α 位为主，高温 β 位为主。",
            keywords: ["稠环芳烃", "萘", "蒽", "菲", "α位"],
          },
        ],
      },
      {
        chapter: "第八章 卤代烃",
        sections: [
          {
            id: "ORG-701",
            title: "卤代烃的分类和命名",
            content: "分类：伯、仲、叔卤代烃。命名：选含卤原子的最长碳链为主链。",
            formula: "",
            mechanism: "",
            conditions: "",
            keywords: ["卤代烃", "伯仲叔", "分类", "命名"],
          },
          {
            id: "ORG-702",
            title: "亲核取代反应 (SN1/SN2)",
            content: "SN1：单分子，两步，碳正离子中间体，外消旋化，叔 > 仲 > 伯 SN2：双分子，一步，背面进攻，构型翻转，伯 > 仲 > 叔",
            formula: "",
            mechanism: "SN1：第一步卤离子离去形成碳正离子（决速步），第二步亲核试剂进攻。SN2：亲核试剂从背面进攻，同时离去基团离开，构型翻转（Walden 翻转）。",
            conditions: "SN1：极性溶剂，叔卤代烷有利；SN2：非极性溶剂，伯卤代烷有利。",
            keywords: ["SN1", "SN2", "亲核取代", "碳正离子", "构型翻转", "Walden"],
          },
          {
            id: "ORG-703",
            title: "消除反应 (E1/E2)",
            content: "E1：单分子，两步，碳正离子中间体 E2：双分子，一步，反式消除",
            formula: "",
            mechanism: "E1：与 SN1 竞争，第一步形成碳正离子，第二步脱去 β-H。E2：与 SN2 竞争，碱夺取 β-H，同时离去基团离开，反式共平面消除。",
            conditions: "E1：极性溶剂，高温；E2：强碱，高温。札伊采夫规则：消除产物以取代基多的烯烃为主。",
            keywords: ["消除反应", "E1", "E2", "反式消除"],
          },
          {
            id: "ORG-704",
            title: "格氏试剂",
            content: "卤代烷 + Mg → RMgX。与醛酮反应生成醇。与 CO2 反应生成羧酸。",
            formula: "\\chemfig{R-X} + Mg \\xrightarrow{无水乙醚} \\chemfig{R-MgX}",
            mechanism: "格氏试剂是强亲核试剂和强碱。与醛反应生成伯醇，与酮反应生成仲醇，与 CO₂ 反应生成多一个碳的羧酸。",
            conditions: "无水乙醚或 THF 溶剂，严格无水无氧。",
            keywords: ["格氏试剂", "RMgX", "醇", "羧酸"],
          },
        ],
      },
      {
        chapter: "第九章 醇和醚",
        sections: [
          {
            id: "ORG-801",
            title: "醇的结构和命名",
            content: "醇：羟基 (-OH) 连在饱和碳上。分类：伯、仲、叔醇。命名：选含羟基的最长碳链为主链。",
            keywords: ["醇", "羟基", "伯仲叔", "命名"],
          },
          {
            id: "ORG-802",
            title: "醇的物理性质",
            content: "沸点高：氢键作用。水溶性：低级醇与水互溶。",
            keywords: ["醇", "沸点", "氢键", "水溶性"],
          },
          {
            id: "ORG-803",
            title: "醇的化学性质 - 与活泼金属反应",
            content: "醇 + Na → 醇钠 + H2。酸性：甲醇 > 伯醇 > 仲醇 > 叔醇。",
            formula: "\\chemfig{2 R-OH} + 2 Na \\to \\chemfig{2 R-ONa} + H_2\\uparrow",
            mechanism: "醇羟基的 O-H 键断裂，氢被金属钠取代，放出氢气。烷基给电子效应使氧上电子云密度增加，O-H 键极性减弱，酸性降低。",
            conditions: "无水条件，钠块缓慢反应。",
            keywords: ["醇钠", "Na", "酸性"],
          },
          {
            id: "ORG-804",
            title: "醇的化学性质 - 与氢卤酸反应",
            content: "醇 + HX → 卤代烷 + H2O。活性：叔醇 > 仲醇 > 伯醇。Lucas 试剂鉴别伯仲叔醇。",
            formula: "\\chemfig{R-OH} + HX \\to \\chemfig{R-X} + H_2O",
            mechanism: "叔醇和仲醇：SN1 机理，先质子化，再脱水形成碳正离子，最后卤离子进攻。伯醇：SN2 机理。",
            conditions: "Lucas 试剂（浓 HCl + ZnCl₂）：叔醇立即浑浊，仲醇数分钟浑浊，伯醇室温不反应。",
            keywords: ["氢卤酸", "卤代烷", "Lucas试剂", "鉴别"],
          },
          {
            id: "ORG-805",
            title: "醇的化学性质 - 脱水反应",
            content: "分子内脱水：醇 → 烯烃（酸催化，高温） 分子间脱水：醇 → 醚（酸催化，低温）",
            formula: "\\chemfig{CH_3CH_2OH} \\xrightarrow{浓H_2SO_4, 170^\\circ C} \\chemfig{CH_2=CH_2} + H_2O",
            mechanism: "分子内脱水：E1 机理，先质子化，再脱水形成碳正离子，最后脱去 β-H。札伊采夫规则：取代基多的烯烃为主。",
            conditions: "分子内脱水：浓 H₂SO₄，高温（170°C）；分子间脱水：浓 H₂SO₄，低温（140°C）。",
            keywords: ["脱水", "烯烃", "醚", "分子内", "分子间"],
          },
          {
            id: "ORG-806",
            title: "醇的氧化反应",
            content: "伯醇 → 醛 → 羧酸 仲醇 → 酮 叔醇：难氧化（条件剧烈时断裂）",
            formula: "\\chemfig{R-CH_2OH} \\xrightarrow{KMnO_4, H^+} \\chemfig{R-CHO} \\xrightarrow{KMnO_4, H^+} \\chemfig{R-COOH}",
            mechanism: "伯醇先氧化为醛，醛继续氧化为羧酸。仲醇氧化为酮，酮难继续氧化。叔醇无 α-H，条件剧烈时碳碳键断裂。",
            conditions: "强氧化：KMnO₄/K₂Cr₂O₇，酸性，加热；温和氧化：PCC（吡啶氯铬酸盐），伯醇停在醛。",
            keywords: ["氧化", "伯醇", "仲醇", "叔醇", "醛", "酮", "羧酸"],
          },
          {
            id: "ORG-807",
            title: "醚的结构和性质",
            content: "醚：C-O-C。性质稳定，常用溶剂。醚键的断裂：HI 或 HBr。",
            formula: "\\chemfig{R-O-R'}",
            mechanism: "醚键断裂：浓 HI 或 HBr 加热，醚氧先质子化，然后卤离子进攻取代基，生成醇和卤代烷。",
            conditions: "浓 HI 或 HBr，加热。芳基烷基醚断裂生成酚和卤代烷。",
            keywords: ["醚", "醚键", "溶剂", "断裂"],
          },
        ],
      },
      {
        chapter: "第十章 醛和酮",
        sections: [
          {
            id: "ORG-901",
            title: "醛和酮的结构",
            content: "羰基 C=O。醛：-CHO（端基） 酮：C=O（中间）。sp2 杂化，平面构型。",
            keywords: ["醛", "酮", "羰基", "C=O", "sp2杂化"],
          },
          {
            id: "ORG-902",
            title: "醛和酮的命名",
            content: "选含羰基的最长碳链为主链，编号从靠近羰基的一端开始。",
            keywords: ["命名", "羰基编号", "主链"],
          },
          {
            id: "ORG-903",
            title: "羰基的亲核加成反应",
            content: "1. 加 HCN：α-羟基腈 2. 加 NaHSO3：α-羟基磺酸钠 3. 加 RMgX：醇 4. 加醇：缩醛/缩酮 5. 加氨衍生物：肟、腙等",
            formula: "\\chemfig{R-CHO} + HCN \\to \\chemfig{R-CH(OH)-CN}",
            mechanism: "亲核加成机理：亲核试剂进攻羰基碳，π 键断裂，氧带负电，再质子化。羰基碳正电性越强，反应越容易。",
            conditions: "HCN：碱催化；NaHSO₃：饱和溶液，醛和甲基酮；格氏试剂：无水乙醚；缩醛：干燥 HCl 催化。",
            keywords: ["亲核加成", "HCN", "NaHSO3", "格氏试剂", "缩醛", "肟", "腙"],
          },
          {
            id: "ORG-904",
            title: "醛酮的氧化反应",
            content: "醛易氧化：Tollens 试剂（银镜反应）、Fehling 试剂（砖红色沉淀） 酮难氧化",
            formula: "\\chemfig{R-CHO} + 2 Ag(NH_3)_2OH \\to \\chemfig{R-COONH_4} + 2 Ag\\downarrow + 3 NH_3 + H_2O",
            mechanism: "醛基的 C-H 键易被氧化为 C-OH（羧基）。酮羰基两侧都是碳，难以氧化。",
            conditions: "Tollens 试剂：银氨溶液，水浴加热，银镜反应；Fehling 试剂：硫酸铜+酒石酸钾钠+NaOH，砖红色沉淀（Cu₂O）。",
            keywords: ["氧化", "Tollens", "Fehling", "银镜反应", "醛"],
          },
          {
            id: "ORG-905",
            title: "醛酮的还原反应",
            content: "1. 催化加氢：醇 2. NaBH4：醇（温和） 3. LiAlH4：醇（强） 4. Clemmensen 还原：亚甲基",
            formula: "\\chemfig{R-CHO} \\xrightarrow{NaBH_4, EtOH} \\chemfig{R-CH_2OH}",
            mechanism: "催化加氢：H₂/Pd，C=O 还原为 CH-OH。NaBH₄：温和还原剂，只还原醛酮。LiAlH₄：强还原剂，还原醛酮羧酸酯。Clemmensen：Zn-Hg/HCl，羰基还原为亚甲基。",
            conditions: "NaBH₄：乙醇溶剂，室温；LiAlH₄：无水乙醚；Clemmensen：浓 HCl，回流。",
            keywords: ["还原", "NaBH4", "LiAlH4", "Clemmensen", "亚甲基"],
          },
          {
            id: "ORG-906",
            title: "羟醛缩合反应",
            content: "稀碱催化下，两分子醛（有 α-H）缩合生成 β-羟基醛。加热脱水生成 α,β-不饱和醛。",
            formula: "\\chemfig{2 CH_3CHO} \\xrightarrow{稀OH^-} \\chemfig{CH_3CH(OH)CH_2CHO}",
            mechanism: "第一步：碱夺取 α-H，形成烯醇负离子；第二步：烯醇负离子进攻另一分子醛的羰基，发生亲核加成；第三步：质子化生成 β-羟基醛。",
            conditions: "稀 NaOH 水溶液，低温（5°C）。加热脱水生成 α,β-不饱和醛。",
            keywords: ["羟醛缩合", "α-H", "β-羟基醛", "脱水"],
          },
          {
            id: "ORG-907",
            title: "卤仿反应",
            content: "甲基酮 + 卤素 + 碱 → 卤仿（CHX3）+ 羧酸盐。碘仿反应用于鉴别甲基酮。",
            formula: "\\chemfig{CH_3CO-R} + 3 I_2 + 4 NaOH \\to \\chemfig{CHI_3}\\downarrow + \\chemfig{R-COONa} + 3 NaI + 3 H_2O",
            mechanism: "甲基酮的三个 α-H 被卤素取代，生成 CX₃-CO-R，然后碱断裂 C-C 键，生成卤仿和羧酸盐。",
            conditions: "I₂/NaOH，加热。碘仿（CHI₃）为黄色沉淀，用于鉴别甲基酮和能氧化为甲基酮的醇。",
            keywords: ["卤仿反应", "甲基酮", "碘仿", "鉴别"],
          },
        ],
      },
      {
        chapter: "第十一章 羧酸",
        sections: [
          {
            id: "ORG-1001",
            title: "羧酸的结构和命名",
            content: "羧基 -COOH。命名：选含羧基的最长碳链为主链，编号从羧基碳开始。",
            formula: "\\chemfig{R-COOH}",
            mechanism: "羧基中羰基和羟基形成 p-π 共轭，羧基碳的亲电性降低，羟基的 O-H 键极性增强。",
            conditions: "",
            keywords: ["羧酸", "羧基", "命名", "COOH"],
          },
          {
            id: "ORG-1002",
            title: "羧酸的酸性",
            content: "羧酸有酸性（pKa ~5）。取代基对酸性的影响：吸电子基增强酸性，给电子基减弱酸性。",
            formula: "\\chemfig{R-COOH} \\rightleftharpoons \\chemfig{R-COO^-} + H^+",
            mechanism: "羧酸根负离子的负电荷通过 p-π 共轭分散到两个氧原子上，稳定性高，所以羧酸有明显酸性。吸电子基进一步分散负电荷，增强酸性。",
            conditions: "",
            keywords: ["酸性", "pKa", "吸电子基", "给电子基"],
          },
          {
            id: "ORG-1003",
            title: "羧酸的化学反应",
            content: "1. 成盐反应 2. 生成酰卤 3. 生成酸酐 4. 生成酯（Fischer 酯化） 5. 生成酰胺",
            formula: "\\chemfig{R-COOH} + R'OH \\xrightleftharpoons{H^+} \\chemfig{R-COOR'} + H_2O",
            mechanism: "Fischer 酯化：酸催化，亲核酰基取代机理。羰基先质子化，增强羰基碳亲电性，然后醇进攻，再脱水。",
            conditions: "成盐：NaOH/Na₂CO₃；酰卤：SOCl₂/PCl₃；酯化：浓 H₂SO₄，回流；酰胺：氨，加热。",
            keywords: ["成盐", "酰卤", "酸酐", "酯化", "酰胺"],
          },
          {
            id: "ORG-1004",
            title: "羧酸的还原",
            content: "LiAlH4 还原羧酸生成伯醇。",
            formula: "\\chemfig{R-COOH} \\xrightarrow{LiAlH_4, 无水乙醚} \\chemfig{R-CH_2OH}",
            mechanism: "LiAlH₄ 是强还原剂，将羧基还原为伯醇。NaBH₄ 不能还原羧酸。",
            conditions: "无水乙醚或 THF，严格无水。",
            keywords: ["还原", "LiAlH4", "伯醇"],
          },
          {
            id: "ORG-1005",
            title: "羧酸衍生物",
            content: "酰卤、酸酐、酯、酰胺。水解活性：酰卤 > 酸酐 > 酯 > 酰胺。",
            formula: "",
            mechanism: "亲核酰基取代：亲核试剂进攻羰基，形成四面体中间体，然后离去基团离开。离去基团越容易离开，活性越高。",
            conditions: "水解：酰卤常温，酸酐加热，酯需酸碱催化，酰胺需强酸/强碱长时间回流。",
            keywords: ["羧酸衍生物", "酰卤", "酸酐", "酯", "酰胺", "水解活性"],
          },
        ],
      },
      {
        chapter: "第十二章 含氮化合物",
        sections: [
          {
            id: "ORG-1101",
            title: "硝基化合物",
            content: "硝基 -NO2。芳香族硝基化合物：还原生成苯胺。",
            formula: "\\chemfig{*6(-=-=-NO_2-)} \\xrightarrow{Fe/HCl} \\chemfig{*6(-=-=-NH_2-)}",
            mechanism: "硝基在酸性条件下还原，经过亚硝基、羟胺中间体，最终生成氨基。",
            conditions: "Fe/HCl 或 Sn/HCl，加热。催化氢化：H₂/Pd。",
            keywords: ["硝基化合物", "硝基", "还原", "苯胺"],
          },
          {
            id: "ORG-1102",
            title: "胺的分类和命名",
            content: "胺：氨基 -NH2。分类：伯、仲、叔胺。命名：选含氨基的最长碳链为主链。",
            formula: "",
            mechanism: "",
            conditions: "",
            keywords: ["胺", "氨基", "伯仲叔", "命名"],
          },
          {
            id: "ORG-1103",
            title: "胺的碱性",
            content: "胺有碱性。脂肪胺 > 氨 > 芳香胺。取代基对碱性的影响。",
            formula: "\\chemfig{R-NH_2} + H_2O \\rightleftharpoons \\chemfig{R-NH_3^+} + OH^-",
            mechanism: "胺氮上有孤对电子，能接受质子显碱性。脂肪胺烷基给电子，使氮上电子云密度增加，碱性增强。芳香胺氮孤对电子与苯环共轭，碱性减弱。",
            conditions: "",
            keywords: ["碱性", "脂肪胺", "芳香胺", "取代基"],
          },
          {
            id: "ORG-1104",
            title: "胺的化学反应",
            content: "1. 烷基化 2. 酰基化 3. 与亚硝酸反应 4. 芳香胺的亲电取代",
            formula: "",
            mechanism: "烷基化：氨/胺与卤代烷反应，生成更高阶的胺。酰基化：胺与酰卤/酸酐反应生成酰胺。与亚硝酸：伯胺生成重氮盐，仲胺生成 N-亚硝基胺。",
            conditions: "烷基化：卤代烷，加热；酰基化：酰卤/酸酐，吡啶；重氮化：NaNO₂/HCl，0-5°C。",
            keywords: ["烷基化", "酰基化", "亚硝酸", "亲电取代"],
          },
          {
            id: "ORG-1105",
            title: "重氮盐",
            content: "芳香伯胺 + 亚硝酸 + 低温 → 重氮盐。重氮盐的取代反应和偶联反应。",
            keywords: ["重氮盐", "亚硝酸", "偶联反应"],
          },
        ],
      },
    ],
  },

  // ============================================================
  // 第二本: 药物化学（第三版）- 尤启冬
  // ============================================================
  "药物化学（第三版）": {
    bookCode: "DRUG",
    totalChapters: 20,
    chapters: [
      {
        chapter: "第一章 绪论",
        sections: [
          {
            id: "DRUG-001",
            title: "药物化学的定义和任务",
            content: "药物化学是研究化学药物的结构、制备、性质、构效关系、体内代谢、寻找新药的一门科学。",
            keywords: ["药物化学", "定义", "任务"],
          },
          {
            id: "DRUG-002",
            title: "药物的质量评价",
            content: "1. 有效性 2. 安全性 3. 稳定性 4. 均一性",
            keywords: ["质量评价", "有效性", "安全性", "稳定性"],
          },
        ],
      },
      {
        chapter: "第二章 麻醉药",
        sections: [
          {
            id: "DRUG-101",
            title: "全身麻醉药",
            content: "吸入麻醉药：乙醚、氟烷、恩氟烷、异氟烷。静脉麻醉药：硫喷妥钠、氯胺酮。",
            formula: "",
            mechanism: "作用机制：抑制中枢神经系统，产生意识、感觉和反射消失。吸入麻醉药通过血脑屏障，作用于 GABA_A 受体和 NMDA 受体。",
            conditions: "吸入麻醉药：需挥发罐，控制浓度；静脉麻醉药：静脉注射，起效快。",
            keywords: ["全身麻醉药", "吸入麻醉", "静脉麻醉", "乙醚", "氯胺酮"],
          },
          {
            id: "DRUG-102",
            title: "局部麻醉药",
            content: "酯类：普鲁卡因、丁卡因。酰胺类：利多卡因、布比卡因。构效关系：芳环-中间链-氨基。",
            formula: "",
            mechanism: "作用机制：阻断电压门控 Na⁺ 通道，阻止神经冲动传导。芳环提供脂溶性，中间链决定代谢途径，氨基决定水溶性。",
            conditions: "酯类：血浆假性胆碱酯酶水解，作用时间短；酰胺类：肝脏代谢，作用时间长。",
            keywords: ["局部麻醉药", "普鲁卡因", "利多卡因", "构效关系"],
          },
        ],
      },
      {
        chapter: "第三章 镇静催眠药和抗癫痫药",
        sections: [
          {
            id: "DRUG-201",
            title: "巴比妥类",
            content: "苯巴比妥、异戊巴比妥、硫喷妥钠。作用机制：增强 GABA 介导的 Cl- 内流。",
            formula: "",
            mechanism: "作用机制：与 GABA_A 受体结合，延长 Cl⁻ 通道开放时间，增强抑制性突触传递。脂溶性越高，起效越快，作用时间越短。",
            conditions: "苯巴比妥：长效，抗癫痫；异戊巴比妥：中效，镇静催眠；硫喷妥钠：超短效，静脉麻醉。",
            keywords: ["巴比妥", "苯巴比妥", "GABA", "Cl-"],
          },
          {
            id: "DRUG-202",
            title: "苯二氮䓬类",
            content: "地西泮、艾司唑仑、阿普唑仑。作用机制：增强 GABA 与受体的结合。",
            formula: "",
            mechanism: "作用机制：与 GABA_A 受体结合，增加 Cl⁻ 通道开放频率，增强 GABA 的抑制作用。安全性比巴比妥类高。",
            conditions: "地西泮：长效，抗焦虑、催眠；艾司唑仑：中效，催眠；阿普唑仑：短效，抗焦虑。",
            keywords: ["苯二氮䓬", "地西泮", "安定", "GABA"],
          },
          {
            id: "DRUG-203",
            title: "抗癫痫药",
            content: "苯妥英钠、卡马西平、丙戊酸钠。作用机制：稳定细胞膜，抑制异常放电。",
            formula: "",
            mechanism: "苯妥英钠：阻断 Na⁺ 通道，稳定细胞膜；卡马西平：阻断 Na⁺ 通道，用于精神运动性发作；丙戊酸钠：增强 GABA 功能，广谱抗癫痫。",
            conditions: "苯妥英钠：大发作首选；卡马西平：精神运动性发作首选；丙戊酸钠：广谱，各型发作均可。",
            keywords: ["抗癫痫", "苯妥英钠", "卡马西平", "丙戊酸钠"],
          },
        ],
      },
      {
        chapter: "第四章 精神神经疾病治疗药",
        sections: [
          {
            id: "DRUG-301",
            title: "抗精神病药",
            content: "吩噻嗪类：氯丙嗪。丁酰苯类：氟哌啶醇。作用机制：阻断多巴胺受体。",
            formula: "",
            mechanism: "作用机制：阻断中脑-边缘系统和中脑-皮质通路的 D₂ 受体，发挥抗精神病作用。同时阻断黑质-纹状体 D₂ 受体，产生锥体外系副作用。",
            conditions: "氯丙嗪：第一代抗精神病药，副作用多；利培酮：第二代，锥体外系副作用少。",
            keywords: ["抗精神病", "氯丙嗪", "多巴胺受体"],
          },
          {
            id: "DRUG-302",
            title: "抗抑郁药",
            content: "三环类：丙咪嗪。单胺氧化酶抑制剂：吗氯贝胺。SSRIs：氟西汀、帕罗西汀。",
            formula: "",
            mechanism: "三环类：抑制 NA 和 5-HT 再摄取；MAOI：抑制单胺氧化酶，增加单胺类递质；SSRIs：选择性抑制 5-HT 再摄取，副作用少。",
            conditions: "氟西汀（百忧解）：SSRI 类首选，起效慢（2-4 周）。",
            keywords: ["抗抑郁", "氟西汀", "百忧解", "SSRIs"],
          },
        ],
      },
      {
        chapter: "第五章 解热镇痛药和非甾体抗炎药",
        sections: [
          {
            id: "DRUG-401",
            title: "阿司匹林",
            content: "乙酰水杨酸。作用机制：抑制 COX，减少前列腺素合成。临床：解热、镇痛、抗炎、抗血小板。",
            keywords: ["阿司匹林", "乙酰水杨酸", "COX", "前列腺素"],
          },
          {
            id: "DRUG-402",
            title: "对乙酰氨基酚",
            content: "扑热息痛。作用机制：抑制中枢 COX。临床：解热镇痛，抗炎作用弱。",
            keywords: ["对乙酰氨基酚", "扑热息痛", "解热镇痛"],
          },
          {
            id: "DRUG-403",
            title: "非甾体抗炎药 (NSAIDs)",
            content: "布洛芬、萘普生、双氯芬酸、吲哚美辛。作用机制：抑制 COX。分类：选择性 COX-2 抑制剂。",
            keywords: ["NSAIDs", "布洛芬", "萘普生", "COX-2"],
          },
        ],
      },
      {
        chapter: "第六章 镇痛药",
        sections: [
          {
            id: "DRUG-501",
            title: "吗啡及其衍生物",
            content: "吗啡、可待因、海洛因。作用机制：激动阿片受体。临床：镇痛、镇咳、止泻。",
            formula: "",
            mechanism: "作用机制：激动中枢神经系统的 μ 阿片受体，抑制 P 物质释放，阻断痛觉传导。同时抑制呼吸中枢、镇咳、兴奋延髓催吐化学感受区。",
            conditions: "吗啡：强效镇痛，成瘾性强；可待因：镇咳为主，镇痛弱；海洛因：二乙酰吗啡，成瘾性极强。",
            keywords: ["吗啡", "可待因", "阿片受体", "镇痛"],
          },
          {
            id: "DRUG-502",
            title: "合成镇痛药",
            content: "哌替啶、芬太尼、美沙酮。作用机制：激动阿片受体。",
            formula: "",
            mechanism: "作用机制：激动 μ 阿片受体，发挥镇痛作用。结构虽与吗啡不同，但药效团相似（芳环-叔胺-哌啶环）。",
            conditions: "哌替啶：短效，分娩镇痛；芬太尼：强效，静脉麻醉；美沙酮：长效，戒毒替代治疗。",
            keywords: ["合成镇痛药", "哌替啶", "芬太尼", "美沙酮"],
          },
        ],
      },
      {
        chapter: "第七章 心血管系统药物",
        sections: [
          {
            id: "DRUG-601",
            title: "钙通道阻滞剂",
            content: "二氢吡啶类：硝苯地平、尼莫地平。芳烷基胺类：维拉帕米。苯噻氮䓬类：地尔硫卓。",
            formula: "",
            mechanism: "作用机制：阻断电压门控 L-型钙通道，抑制 Ca²⁺ 内流，松弛血管平滑肌，降低心肌收缩力，减慢心率。",
            conditions: "硝苯地平：扩血管强，降压；维拉帕米：负性频率，抗心律失常；地尔硫卓：介于两者之间。",
            keywords: ["钙通道阻滞剂", "硝苯地平", "维拉帕米", "高血压"],
          },
          {
            id: "DRUG-602",
            title: "ACE 抑制剂",
            content: "卡托普利、依那普利。作用机制：抑制血管紧张素转化酶。临床：高血压、心衰。",
            formula: "",
            mechanism: "作用机制：抑制血管紧张素转化酶（ACE），阻止 Ang I 转化为 Ang II，同时抑制缓激肽降解，扩张血管，降低血压。",
            conditions: "干咳为常见副作用（缓激肽蓄积）。禁忌：双侧肾动脉狭窄、妊娠。",
            keywords: ["ACEI", "卡托普利", "依那普利", "高血压"],
          },
          {
            id: "DRUG-603",
            title: "β 受体阻滞剂",
            content: "普萘洛尔、美托洛尔。作用机制：阻断 β 受体。临床：高血压、心绞痛、心律失常。",
            formula: "",
            mechanism: "作用机制：阻断心脏 β₁ 受体，减慢心率，降低心肌收缩力，减少心肌耗氧量。同时阻断肾脏 β₁ 受体，抑制肾素释放。",
            conditions: "普萘洛尔：非选择性（β₁+β₂）；美托洛尔：选择性 β₁。禁忌：支气管哮喘（阻断 β₂ 可诱发哮喘）。",
            keywords: ["β受体阻滞剂", "普萘洛尔", "美托洛尔", "高血压"],
          },
        ],
      },
      {
        chapter: "第十一章 抗生素",
        sections: [
          {
            id: "DRUG-701",
            title: "β-内酰胺类抗生素",
            content: "青霉素类：青霉素G、阿莫西林。头孢菌素类：头孢氨苄、头孢呋辛。作用机制：抑制细胞壁合成。",
            formula: "",
            mechanism: "作用机制：与青霉素结合蛋白（PBPs）结合，抑制转肽酶活性，阻止肽聚糖交联，导致细菌细胞壁缺损，菌体膨胀裂解。",
            conditions: "青霉素 G：革兰阳性菌首选；阿莫西林：广谱，口服有效；头孢类：分代，代数越高革兰阴性菌覆盖越广。",
            keywords: ["β-内酰胺", "青霉素", "头孢", "细胞壁"],
          },
          {
            id: "DRUG-702",
            title: "大环内酯类抗生素",
            content: "红霉素、阿奇霉素、克拉霉素。作用机制：抑制细菌蛋白质合成。",
            formula: "",
            mechanism: "作用机制：与细菌核糖体 50S 亚基结合，抑制转肽作用和 mRNA 移位，阻止蛋白质合成。",
            conditions: "红霉素：耐青霉素的革兰阳性菌；阿奇霉素：半衰期长，每日一次，非典型病原体首选。",
            keywords: ["大环内酯", "红霉素", "阿奇霉素", "蛋白质合成"],
          },
          {
            id: "DRUG-703",
            title: "氨基糖苷类抗生素",
            content: "链霉素、庆大霉素、阿米卡星。作用机制：抑制细菌蛋白质合成。耳毒性、肾毒性。",
            formula: "",
            mechanism: "作用机制：与细菌核糖体 30S 亚基结合，抑制蛋白质合成，同时导致细胞膜缺损，通透性增加。",
            conditions: "耳毒性（前庭功能损害、听力损害）、肾毒性、神经肌肉阻滞。需监测血药浓度。",
            keywords: ["氨基糖苷", "链霉素", "庆大霉素", "耳毒性"],
          },
          {
            id: "DRUG-704",
            title: "四环素类抗生素",
            content: "四环素、多西环素、米诺环素。作用机制：抑制细菌蛋白质合成。",
            formula: "",
            mechanism: "作用机制：与细菌核糖体 30S 亚基结合，抑制氨酰-tRNA 进入 A 位，阻止蛋白质合成。",
            conditions: "影响骨骼和牙齿发育（与钙螯合），孕妇和 8 岁以下儿童禁用。",
            keywords: ["四环素", "多西环素", "蛋白质合成"],
          },
        ],
      },
      {
        chapter: "第十二章 合成抗菌药",
        sections: [
          {
            id: "DRUG-801",
            title: "喹诺酮类抗菌药",
            content: "诺氟沙星、环丙沙星、左氧氟沙星。作用机制：抑制 DNA 回旋酶。",
            formula: "",
            mechanism: "作用机制：抑制细菌 DNA 回旋酶（拓扑异构酶 II）和拓扑异构酶 IV，阻止 DNA 复制和转录。",
            conditions: "环丙沙星：革兰阴性菌活性强；左氧氟沙星：呼吸喹诺酮，非典型病原体有效。软骨损伤，孕妇和儿童禁用。",
            keywords: ["喹诺酮", "环丙沙星", "左氧氟沙星", "DNA回旋酶"],
            keywords: ["喹诺酮", "环丙沙星", "左氧氟沙星", "DNA回旋酶"],
          },
          {
            id: "DRUG-802",
            title: "磺胺类抗菌药",
            content: "磺胺甲恶唑、甲氧苄啶。作用机制：抑制叶酸合成。",
            keywords: ["磺胺", "叶酸", "抗菌"],
          },
        ],
      },
      {
        chapter: "第十四章 抗肿瘤药物",
        sections: [
          {
            id: "DRUG-901",
            title: "烷化剂",
            content: "环磷酰胺、氮芥。作用机制：与 DNA 共价结合，破坏 DNA 结构和功能。",
            keywords: ["烷化剂", "环磷酰胺", "氮芥", "DNA"],
          },
          {
            id: "DRUG-902",
            title: "抗代谢物",
            content: "甲氨蝶呤、氟尿嘧啶、阿糖胞苷。作用机制：干扰核酸合成。",
            keywords: ["抗代谢物", "甲氨蝶呤", "氟尿嘧啶", "核酸合成"],
          },
          {
            id: "DRUG-903",
            title: "天然抗肿瘤药",
            content: "长春新碱、紫杉醇。作用机制：抑制微管蛋白聚合/解聚。",
            keywords: ["长春新碱", "紫杉醇", "微管"],
          },
        ],
      },
    ],
  },

  // ============================================================
  // 第三本: 药理学（第九版）- 杨宝峰
  // ============================================================
  "药理学（第九版）": {
    bookCode: "PHARM",
    totalChapters: 48,
    chapters: [
      {
        chapter: "第一章 药理学总论",
        sections: [
          {
            id: "PHARM-001",
            title: "药物效应动力学 (药效学)",
            content: "研究药物对机体的作用及作用机制。包括：药物作用、药理效应、治疗效果、不良反应。",
            formula: "",
            mechanism: "药效学核心：药物与受体结合 → 信号转导 → 细胞反应 → 器官效应 → 整体效应。治疗效果分为对因治疗和对症治疗。",
            conditions: "",
            keywords: ["药效学", "药物作用", "药理效应", "不良反应"],
          },
          {
            id: "PHARM-002",
            title: "药物代谢动力学 (药动学)",
            content: "研究机体对药物的作用。包括：吸收、分布、代谢、排泄。",
            formula: "",
            mechanism: "药动学核心：ADME 过程。吸收（Absorption）→ 分布（Distribution）→ 代谢（Metabolism）→ 排泄（Excretion）。",
            conditions: "",
            keywords: ["药动学", "吸收", "分布", "代谢", "排泄"],
          },
          {
            id: "PHARM-003",
            title: "不良反应分类",
            content: "1. 副反应 2. 毒性反应 3. 后遗效应 4. 停药反应 5. 变态反应 6. 特异质反应",
            formula: "",
            mechanism: "副反应：治疗剂量下出现的与治疗目的无关的作用；毒性反应：剂量过大或蓄积过多；后遗效应：停药后血药浓度已降至阈浓度以下残存的药理效应；停药反应：突然停药后原有疾病加剧。",
            conditions: "",
            keywords: ["不良反应", "副反应", "毒性反应", "变态反应"],
          },
        ],
      },
      {
        chapter: "第二章 药物代谢动力学",
        sections: [
          {
            id: "PHARM-101",
            title: "药物的吸收",
            content: "吸收：药物从给药部位进入血液循环的过程。给药途径：口服、舌下、直肠、吸入、注射、经皮。",
            formula: "",
            mechanism: "口服吸收：经胃肠道 → 门静脉 → 肝脏（首过效应）→ 体循环。首过效应大的药物生物利用度低。",
            conditions: "口服：方便但有首过效应；舌下/直肠：无首过效应；静脉注射：直接入血，无吸收过程。",
            keywords: ["吸收", "给药途径", "首过效应"],
          },
          {
            id: "PHARM-102",
            title: "药物的分布",
            content: "分布：药物从血循环到达机体各组织的过程。影响因素：血浆蛋白结合率、器官血流量、组织亲和力、屏障。",
            formula: "",
            mechanism: "药物与血浆蛋白结合后不能跨膜转运，暂时储存于血液中。血脑屏障：只允许脂溶性高、分子量小的药物通过。",
            conditions: "血浆蛋白结合率高的药物作用时间长；脂溶性高的药物易通过血脑屏障。",
            keywords: ["分布", "血浆蛋白结合", "血脑屏障"],
          },
          {
            id: "PHARM-103",
            title: "药物的代谢",
            content: "代谢：药物在体内发生化学结构改变的过程。主要器官：肝脏。酶系：细胞色素 P450 酶系。",
            formula: "",
            mechanism: "I 相反应：氧化、还原、水解，引入或暴露官能团；II 相反应：结合反应，与葡萄糖醛酸、硫酸等结合，增加水溶性。",
            conditions: "P450 酶诱导剂（如苯巴比妥）加速药物代谢；P450 酶抑制剂（如西咪替丁）减慢药物代谢。",
            keywords: ["代谢", "肝脏", "P450", "酶系"],
          },
          {
            id: "PHARM-104",
            title: "药物的排泄",
            content: "排泄：药物及其代谢产物排出体外的过程。主要器官：肾脏。其他：胆汁、乳汁、唾液、汗液。",
            formula: "",
            mechanism: "肾脏排泄：肾小球滤过 + 肾小管分泌 + 肾小管重吸收。酸化尿液可加速弱酸性药物排泄，碱化尿液可加速弱碱性药物排泄。",
            conditions: "肝功能不全时胆汁排泄减少；肾功能不全时经肾排泄的药物半衰期延长。",
            keywords: ["排泄", "肾脏", "胆汁", "乳汁"],
          },
        ],
      },
      {
        chapter: "第三章 药物效应动力学",
        sections: [
          {
            id: "PHARM-201",
            title: "受体理论",
            content: "受体：一类介导细胞信号转导的功能蛋白质。配体：能与受体特异性结合的物质。",
            formula: "",
            mechanism: "受体特性：特异性、饱和性、可逆性、高亲和力。激动药：既有亲和力又有内在活性；拮抗药：有亲和力无内在活性。",
            conditions: "",
            keywords: ["受体", "配体", "信号转导"],
          },
          {
            id: "PHARM-202",
            title: "激动药和拮抗药",
            content: "激动药：既有亲和力又有内在活性。拮抗药：有亲和力但无内在活性。部分激动药：内在活性不强。",
            keywords: ["激动药", "拮抗药", "亲和力", "内在活性"],
          },
          {
            id: "PHARM-203",
            title: "受体类型",
            content: "1. G 蛋白偶联受体 (GPCR) 2. 离子通道受体 3. 酶活性受体 4. 细胞核激素受体",
            keywords: ["GPCR", "离子通道", "酶活性受体", "核受体"],
          },
        ],
      },
    ],
  },

  // ============================================================
  // 第四本: 药物合成反应（第四版）- 闻韧
  // ============================================================
  "药物合成反应（第四版）": {
    bookCode: "SYNTH",
    totalChapters: 12,
    chapters: [
      {
        chapter: "第一章 卤化反应",
        sections: [
          {
            id: "SYNTH-001",
            title: "卤化反应概述",
            content: "卤化反应：在有机分子中引入卤素原子的反应。包括：不饱和烃的卤加成、饱和碳上的卤取代、芳香环上的卤取代。",
            keywords: ["卤化反应", "卤素", "卤加成", "卤取代"],
          },
        ],
      },
      {
        chapter: "第二章 烃化反应",
        sections: [
          {
            id: "SYNTH-101",
            title: "烃化反应概述",
            content: "烃化反应：在有机分子中引入烃基的反应。包括：C-烃化、N-烃化、O-烃化。",
            keywords: ["烃化反应", "C-烃化", "N-烃化", "O-烃化"],
          },
        ],
      },
      {
        chapter: "第五章 酰化反应",
        sections: [
          {
            id: "SYNTH-201",
            title: "酰化反应概述",
            content: "酰化反应：在有机分子中引入酰基的反应。包括：C-酰化、N-酰化、O-酰化。",
            keywords: ["酰化反应", "酰基", "C-酰化", "N-酰化", "O-酰化"],
          },
          {
            id: "SYNTH-202",
            title: "阿司匹林的合成",
            content: "水杨酸 + 乙酸酐 → 阿司匹林 + 乙酸。催化剂：浓硫酸。反应条件：加热 80-90°C。",
            keywords: ["阿司匹林", "水杨酸", "乙酸酐", "酯化"],
          },
        ],
      },
    ],
  },

  // ============================================================
  // 第五本: 生物化学与分子生物学（第10版）- 高国全
  // ============================================================
  "生物化学与分子生物学（第10版）": {
    bookCode: "BIO",
    totalChapters: 26,
    chapters: [
      {
        chapter: "第一章 蛋白质的结构与功能",
        sections: [
          {
            id: "BIO-001",
            title: "氨基酸",
            content: "蛋白质的基本组成单位。20 种标准氨基酸。分类：非极性、极性中性、酸性、碱性。",
            keywords: ["氨基酸", "蛋白质", "20种氨基酸"],
          },
          {
            id: "BIO-002",
            title: "蛋白质的分子结构",
            content: "一级结构：氨基酸序列。二级结构：α-螺旋、β-折叠。三级结构：整条肽链的空间排布。四级结构：亚基的聚合。",
            keywords: ["蛋白质结构", "一级", "二级", "三级", "四级", "α-螺旋", "β-折叠"],
          },
        ],
      },
      {
        chapter: "第六章 糖代谢",
        sections: [
          {
            id: "BIO-101",
            title: "糖酵解途径 (EMP)",
            content: "葡萄糖 → 2 丙酮酸。净生成 2 ATP + 2 NADH。关键酶：己糖激酶、磷酸果糖激酶-1、丙酮酸激酶。",
            keywords: ["糖酵解", "EMP", "丙酮酸", "ATP", "关键酶"],
          },
          {
            id: "BIO-102",
            title: "三羧酸循环 (TCA)",
            content: "乙酰 CoA → CO2 + H2O。在线粒体进行。关键酶：柠檬酸合酶、异柠檬酸脱氢酶、α-酮戊二酸脱氢酶。",
            keywords: ["三羧酸循环", "TCA", "乙酰CoA", "线粒体"],
          },
          {
            id: "BIO-103",
            title: "磷酸戊糖途径",
            content: "葡萄糖 → 核糖 + NADPH。意义：提供 NADPH 和核糖。",
            keywords: ["磷酸戊糖途径", "核糖", "NADPH"],
          },
        ],
      },
    ],
  },
};

// 导出全局变量
// TEXTBOOK_KNOWLEDGE_BASE

// 挂载到全局对象
window.TEXTBOOK_KNOWLEDGE_BASE = TEXTBOOK_KNOWLEDGE_BASE;
